#------------------------------------------------------------------------------
# compare_verner2013.R
#
# This file runs a simulation of continuous exposure of 1 mg/kg/d to a human
# mother from her birth until she reaches age 28 y. The simulation provides the
# same exposure to the infant after weaning (when the woman reaches age 26 y).
#
# Figures are generated to compare model-predicted mother and offspring
# concentrations with those generated using the Verner et al. (2013) model.
#
# Author: Dustin Kapraun, U.S. EPA, April 2021
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
#script.dir = dirname(sys.frame(1)$ofile)
#setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")

# Save plots to files?
save_plots = TRUE

# Which substance?
# substance = "xxx"
# substance = "aroclor"
# substance = "hcb"
substance = "pcb153"

if (substance == "aroclor") {
  HL = 48665
} else if (substance == "hcb") {
  HL = 2190
} else if (substance == "pcb153") {
  HL = 5256
} else {
  cat(sprintf("Substance '%s' not recognized.\n", substance))
}

# Load output from human simulation of 1 mg/kg/d exposure with Verner et al.
# (2013) model.
verner_file = sprintf("Verner_Kapraun_Predictions_%s.csv", substance)
verner_df = read.csv(verner_file, header=TRUE)
verner_df["t_days"] = verner_df["t"] / 24
verner_df["t_years"] = verner_df["t_days"] / 365
t_concep = 24.25
t_birth = 25.0
t_wean = 26.0

# # Plot the mass balance (amount that has entered - amount in the system -
# # amount that has left) vs. time.
# A_m = verner_df[ , "c_mother_kg"] * verner_df[ , "bw_mother_k"]
# A_i = verner_df[ , "c_child_kg"] * verner_df[ , "bw_child_k"]
# T_in = verner_df[ , "t_in"]
# T_out = verner_df[ , "t_out"]
# A_bal = T_in - A_m - A_i - T_out
# T_out_i = verner_df[ , "t_elimination_child"]
# T_out_m = T_out - T_out_i
# 
# if (save_plots) {
#   file_name = sprintf("./Output/verner_balance_%s.tif", substance)
#   tiff(file_name, units="in", width=6, height=6, res=300)
# }
# plot(verner_df[ , "t_years"], A_bal, type='l', lty=1,
#      lwd=2, col=vcol[1], xlab="Maternal Age (y)", ylab="Mass Balance (mg)",
#      xlim=c(24.25, 26))
# abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
# if (save_plots) {
#   dev.off()
# }


#------------------------------------------------------------------------------

# Simulate the same exposure scenario with our model.
p = init_human_p()
p["d_m"] = 1
# p["F_milk"] = 0.058      # Default value is 0.039.
p["half_life"] = HL
t_start = -24.25 * 365
t_end = 3.75 * 365
times = seq(from=t_start, to=t_end, by=0.25)
out = human_sim(times=times, p=p)
t_days = out[ , "time"] - t_start
t_years = t_days / 365
out = cbind(out, t_days=t_days, t_years=t_years)


# Plot mass balance (amount that has entered - amount in the system -
# amount that has left) vs. time.
if (save_plots) {
  file_name = sprintf("./Output/kapraun_balance_%s.tif", substance)
  tiff(file_name, units="in", width=6, height=6, res=300)
}
plot(out[ , "t_years"], out[ , "A_bal"], type='l', lty=1,
     lwd=2, col=vcol[1], xlab="Maternal Age (y)", ylab="Mass Balance (mg)")
if (save_plots) {
  dev.off()
}

# Plot concentration vs. time.
if (save_plots) {
    file_name = sprintf("./Output/compare_verner_%s.tif", substance)
    tiff(file_name, units="in", width=6, height=6, res=300)
}
ymax = max(c(verner_df[ , "c_mother_kg"],
             verner_df[ , "c_child_kg"],
             out[ , "C_m"],
             out[ , "C_i"]))
plot(verner_df[ , "t_years"], verner_df[ , "c_mother_kg"], type='l', lty=1,
     lwd=2, col=vcol[1], xlab="Maternal Age (y)", ylab="Concentration (mg/kg)",
     log="y", ylim=c(100, ymax))
lines(verner_df[ , "t_years"], verner_df[ , "c_child_kg"], lty=2, lwd=2,
      col=vcol[2])
lines(out[ , "t_years"], out[ , "C_m"], lty=3, lwd=2, col=vcol[3])
lines(out[ , "t_years"], out[ , "C_i"], lty=4, lwd=2, col=vcol[4])
abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
legend("topleft", legend=c("Mother (Verner)", "Offspring (Verner)",
                            "Mother (present)", "Offspring (present)"),
       col=vcol[1:4],
       lty=c(1:4), lwd=c(2, 2, 2, 2))
if (save_plots) {
    dev.off()
}


# Compute percent differences for maternal concentrations.
C_m_verner = verner_df[ , "c_mother_kg"]
C_m_df = data.frame(approx(x=out[ , "t_years"], y=out[ , "C_m"],
                    xout=verner_df[ , "t_years"]))
C_m = C_m_df[ , "y"]
C_m_pd = (C_m - C_m_verner) * 200 / (C_m + C_m_verner)
C_m_pd_max = max(abs(C_m_pd[!is.na(C_m_pd)]))
cat("Maximum absolute percent difference in maternal concentrations: ",
    C_m_pd_max, "%\n", sep="")


# Compute percent differences for offspring concentrations.
C_i_verner = verner_df[ , "c_child_kg"]
C_i_df = data.frame(approx(x=out[ , "t_years"], y=out[ , "C_i"],
                           xout=verner_df[ , "t_years"]))
C_i = C_i_df[ , "y"]
C_i_pd = (C_i - C_i_verner) * 200 / (C_i + C_i_verner)
C_i_pd_max = max(abs(C_i_pd[C_i_verner > 0]))
cat("Maximum absolute percent difference in offspring concentrations: ",
    C_i_pd_max, "%\n", sep="")


# Plot concentration vs. time with focus on the period from conception to
# weaning.
if (save_plots) {
  file_name = sprintf("./Output/compare_verner_%s_zoom.tif", substance)
  tiff(file_name, units="in", width=6, height=6, res=300)
}
ymax = max(c(verner_df[ , "c_mother_kg"],
             verner_df[ , "c_child_kg"],
             out[ , "C_m"],
             out[ , "C_i"]))
plot(verner_df[ , "t_years"], verner_df[ , "c_mother_kg"], type='l', lty=1,
     lwd=2, col=vcol[1], xlab="Maternal Age (y)", ylab="Concentration (mg/kg)",
     xlim=c(24.25, 26),
     ylim=c(100, ymax))
lines(verner_df[ , "t_years"], verner_df[ , "c_child_kg"], lty=2, lwd=2,
      col=vcol[2])
lines(out[ , "t_years"], out[ , "C_m"], lty=3, lwd=2, col=vcol[3])
lines(out[ , "t_years"], out[ , "C_i"], lty=4, lwd=2, col=vcol[4])
abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
legend("topleft", legend=c("Mother (Verner)", "Offspring (Verner)",
                           "Mother (present)", "Offspring (present)"),
       col=vcol[1:4],
       lty=c(1:4), lwd=c(2, 2, 2, 2))
if (save_plots) {
  dev.off()
}


# # Plot maternal body mass vs. time.
# if (save_plots) {
#   file_name = sprintf("./Output/compare_verner_%s_maternal_mass.tif",
#                       substance)
#   tiff(file_name, units="in", width=6, height=6, res=300)
# }
# plot(verner_df[ , "t_years"], verner_df[ , "bw_mother_k"], type='l', lty=1,
#      lwd=2, col=vcol[1], xlab="Maternal Age (y)",
#      ylab="Maternal Body Mass (kg)",
#      ylim=c(0, 85))
# lines(out[ , "t_years"], out[ , "M_mf"], lty=2, lwd=2, col=vcol[2])
# abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
# legend("bottomright", legend=c("Verner", "Kapraun"),
#        col=vcol[1:2], lty=c(1:2), lwd=c(2, 2))
# if (save_plots) {
#   dev.off()
# }


# # Plot offspring body mass vs. time.
# if (save_plots) {
#   file_name = sprintf("./Output/compare_verner_%s_offspring_mass.tif",
#                       substance)
#   tiff(file_name, units="in", width=6, height=6, res=300)
# }
# plot(verner_df[ , "t_years"], verner_df[ , "bw_child_k"], type='l', lty=1,
#      lwd=2, col=vcol[1], xlab="Maternal Age (y)",
#      ylab="Fetus/Infant Body Mass (kg)",
#      xlim=c(24.25, 28))
# lines(out[ , "t_years"], out[ , "M_i"], lty=2, lwd=2, col=vcol[2])
# abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
# legend("bottomright", legend=c("Verner", "Kapraun"),
#        col=vcol[1:2], lty=c(1:2), lwd=c(2, 2))
# if (save_plots) {
#   dev.off()
# }

#------------------------------------------------------------------------------

# Plot maternal amount vs. time with focus on the period from conception to
# weaning.
if (save_plots) {
  file_name = sprintf("./Output/amount_test_%s.tif", substance)
  tiff(file_name, units="in", width=6, height=6, res=300)
}
plot(out[ , "t_years"], out[ , "A_mf"], type='l', lty=1,
     lwd=2, col=vcol[1], xlab="Maternal Age (y)", ylab="Amount (mg)",
     xlim=c(24.25, 26))
abline(v=c(t_concep, t_birth, t_wean), lty=3, col="grey")
if (save_plots) {
  dev.off()
}

# -----------------------------------------------------------------------------