#------------------------------------------------------------------------------
# hcb_nakashima1997_study1_mc.R
#
# This file runs simulations of the Nakashima et al. (1997) study 1 of HCB in
# rats (dams and pups). Briefly, dams were dosed at 35.1 nmol per g of diet
# from conception through 16 days post-partum. Two dams ("pregnant" dams) were
# sacrificed 1 day prior to parturition and observations of HCB concentrations
# in these dams and their pups ("fetuses") were recorded. Three dams ("nursing"
# dams) and their pups were sacrificed 16 days after parturition and
# observations of HCB concentrations in these dams and their pups ("suckling")
# were recorded.
#
# Author: Dustin Kapraun, U.S. EPA, March 2022
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
#script.dir = dirname(sys.frame(1)$ofile)
#setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")

# # Calculate dose (mg/kg) from nominal dose 31.5 nmol per g of diet.
# MW = 284.8    # Molecular weight (g/mol or ng/nmol).
# d_m_calc = 31.5 * MW / 1000

# Calculate dose (mg/kg) from nominal dose 35.1 nmol per 100 g of diet.
MW = 284.8    # Molecular weight (g/mol or ng/nmol).
d_m_calc = 35.1 * MW / (10 ** 5)

# Effective number of fetuses should yield sufficient weight loss to take the
# dam from her late-term mass to her post-natal (PND 16) body mass.
n_f_calc = (0.3905 - 0.247) / 0.0066

# Effective number of infants should be the average number of suckling pups for
# the dams in the study
n_i_calc = mean(c(15, 14, 14))

# Define simulation parameters.
p <- c(M_m_1 = 0.247,      # Maternal mass 1 (kg).
       M_m_2 = 0.3905,     # Maternal mass 2 (kg).
       t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
       t_m_2 = 21,         # Time (d) since conception for maternal mass 2.
       M_i_3 = 0.0286,     # Infant mass 3 (kg).
       t_i_3 = 16,         # Time (d) since birth for infant mass 3.
       n_f = n_f_calc,     # Effective number of fetuses.
       n_i = n_i_calc,     # Number of infants.
       # half_life = 104,    # Half-life (d) from T. Zurlinden model.
       # half_life = 76.1,   # Half-life (d) from T. Zurlinden model.
       # half_life = 94.2,   # Half-life (d) from T. Zurlinden model.
       # half_life = 104,    # ... 9/28/2021.
       half_life = 92.4,   # Half-life (d)  based on 10/6/2021 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       F_m = 0.094,        # Fraction of maternal mass that is fat.
       F_abs = 0.56,       # Fraction of nominal dose that is absorbed.
       food_dose = 1,      # A boolean flag. Dose is delivered in food if
                           #   nonzero.
       d_m = d_m_calc,     # Dose rate (mg/kg/d or mg/kg) to mother.
       t_m_start = 0,      # Time (d) since conception maternal dose starts.
       t_m_end = 38)       # Time (d) since conception maternal dose ends.

p = init_rat_p(p)
t_obs = p[["t_gest"]] + 16
times = seq(from=0, to=t_obs, by=0.1)

# Run simulation.
out <- rat_sim(times=times, p=p)

# Specify number of Monte Carlo simulations.
N_MC = 1000

# Create empty arrays to store simulation results.
C_m_MC = array(numeric(), c(length(times), N_MC))
C_i_MC = array(numeric(), c(length(times), N_MC))

# Seed random number generator.
set.seed(2022)

# Generate random values for influential parameters.
F_abs_MC = rnorm(N_MC, mean=0.56, sd=0.3*0.56)
F_milk_MC = rnorm(N_MC, mean=0.154, sd=0.3*0.154)
F_m_MC = rnorm(N_MC, mean=0.094, sd=0.3*0.094)
r_f_m_MC = rnorm(N_MC, mean=0.35, sd=0.3*0.35)
# half_life_MC = rnorm(N_MC, mean=92.4, sd=25)
half_life_df = read.csv("posterior_halft_HCB.csv")
rand_idx = sample.int(N_MC, size=nrow(half_life_df), replace=TRUE)
half_life_MC = half_life_df[rand_idx, 2]

for (idx in seq(N_MC)) {
    # Define simulation parameters
    p <- c(M_m_1 = 0.247,      # Maternal mass 1 (kg).
           M_m_2 = 0.3905,     # Maternal mass 2 (kg).
           t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
           t_m_2 = 21,         # Time (d) since conception for maternal mass 2.
           M_i_3 = 0.0286,     # Infant mass 3 (kg).
           t_i_3 = 16,         # Time (d) since birth for infant mass 3.
           n_f = n_f_calc,     # Effective number of fetuses.
           n_i = n_i_calc,     # Number of infants.
           half_life = half_life_MC[idx],
           r_f_m = r_f_m_MC[idx],
           F_m = F_m_MC[idx],
           F_milk = F_milk_MC[idx],
           F_abs = F_abs_MC[idx],
           food_dose = 1,      # A boolean flag. Dose is delivered in food if
                               #   nonzero.
           d_m = d_m_calc,     # Dose rate (mg/kg/d or mg/kg) to mother.
           t_m_start = 0,      # Time (d) since conception maternal dose starts.
           t_m_end = 38)       # Time (d) since conception maternal dose ends.
    
    p = init_rat_p(p)
    
    # Run simulation.
    out_MC <- rat_sim(times=times, p=p)
    
    # Save results.
    C_m_MC[ , idx] = out_MC[ , "C_m"]
    C_i_MC[ , idx] = out_MC[ , "C_i"]
}

# Find credible intervals for concentrations.
conf = 0.95
alpha = 1 - conf
lo = alpha / 2
hi = 1 - lo
C_m_lo = apply(C_m_MC, 1, quantile, probs=lo)
C_m_hi = apply(C_m_MC, 1, quantile, probs=hi)
C_m_med = apply(C_m_MC, 1, quantile, probs=0.5)
C_i_lo = apply(C_i_MC, 1, quantile, probs=lo)
C_i_hi = apply(C_i_MC, 1, quantile, probs=hi)
C_i_med = apply(C_i_MC, 1, quantile, probs=0.5)

# Plot all output variables vs. time.
times = out[ , 1]

# # Plot maternal animal dose vs. time.
# plot(times, out[, "D_m"], type='l', xlab="Time (d)",
#      ylab="Maternal Animal Dose (mg/kg/d)")
# 
# # Plot maternal animal mass vs. time.
# plot(times, out[, "M_mf"], type='l', xlab="Time (d)",
#      ylab="Maternal Animal Mass (kg)")
# 
# # Plot maternal animal concentration vs. time.
# plot(times, out[, "C_m"], type='l', xlab="Time (d)",
#      ylab="Maternal Animal Concentration (mg/kg)")
# 
# # Plot filial animal mass vs. time.
# plot(times, out[, "M_i"], type='l', xlab="Time (d)",
#      ylab="Filial Animal Mass (kg)")
# 
# # Plot filial animal body burden vs. time.
# plot(times, out[, "C_i"], type='l', xlab="Time (d)",
#      ylab="Filial Animal Concentration (mg/kg)")


# Plot filial animal mass vs. time along with data.
M_i_data = c(0.0051, 0.0286)
t_data = c(21, 38)

file_name = "./Output/nakashima1997_exp1_filial_mass_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, out[, "M_i"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Pup Mass (kg)")
points(t_data, M_i_data, pch=19, col=vcol[2], cex=1.0)
dev.off()


# Plot maternal animal mass vs. time along with data.
M_m_data = c(0.3905, 0.247)
t_data = c(21, 38)

file_name = "./Output/nakashima1997_exp1_maternal_mass_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, out[, "M_mf"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Dam Mass (kg)")
points(t_data, M_m_data, pch=19, col=vcol[2], cex=1.0)
dev.off()


# Plot maternal animal concentrations vs. time from model along with data.
# C_m_nmol_per_kg = out[, "C_m"] * (1e6) / MW  # Model estimates (nmol/kg).
C_m_nmol_per_kg = C_m_med * (1e6) / MW
C_m_nmol_per_kg_lo = C_m_lo * (1e6) / MW
C_m_nmol_per_kg_hi = C_m_hi * (1e6) / MW
# C_m_blood = c((12.01+15.48)/2, 3.84)          # Blood data (nmol/L)
C_m_blood = c(12.01, 15.48, 3.84)             # Blood data (nmol/L)
C_m_blood_sd = c(NA, NA, 0.24)
# C_m_subcfat = c((546.2+909.5)/2, 49.10)       # Subcutaneous fat data (pmol/g)
C_m_subcfat = c(546.2, 909.5, 49.10)          # Subcutaneous fat data (pmol/g)
C_m_subcfat_sd = c(NA, NA, 3.81)
# C_m_perifat = c((445.6 + 358.2)/2, 145.9)     # Perirenal fat data (pmol/g)
C_m_perifat = c(445.6, 358.2, 145.9)          # Perirenal fat data (pmol/g))
C_m_perifat_sd = c(NA, NA, 26.52)
# t_data = c(21, 38)                            # Days since conception
t_data = c(21, 21, 38)                        # Days since conception

file_name = "./Output/nakashima1997_exp1_maternal_concentration_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, C_m_nmol_per_kg, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Maternal Animal Concentration (pmol/g)",
     ylim=c(0, 950))
lines(times, C_m_nmol_per_kg_lo, lty=2, lwd=2, col=vcol[1])
lines(times, C_m_nmol_per_kg_hi, lty=2, lwd=2, col=vcol[1])
points(t_data, C_m_blood, pch=19, col=vcol[2], cex=1.0)
arrows(t_data, C_m_blood-C_m_blood_sd, t_data, C_m_blood+C_m_blood_sd, code=3,
       angle=90, length=0.05, lwd=2, col=vcol[2])
points(t_data, C_m_subcfat, pch=17, col=vcol[3], cex=1.0)
arrows(t_data, C_m_subcfat-C_m_subcfat_sd, t_data, C_m_subcfat+C_m_subcfat_sd,
       code=3, angle=90, length=0.05, lwd=2, col=vcol[3])
points(t_data, C_m_perifat, pch=15, col=vcol[4], cex=1.0)
arrows(t_data, C_m_perifat-C_m_perifat_sd, t_data, C_m_perifat+C_m_perifat_sd,
       code=3, angle=90, length=0.05, lwd=2, col=vcol[4])
# points(t_data, C_m_whole, pch=18, col="black", cex=1.0)
# legend("topleft", c("Model, whole body", "Data, blood", "Data, subcutaneous fat",
#                     "Data, perirenal fat", "Estimate, whole body"),
#        col=c(vcol[1:4], "black"), lty=c(1, NA, NA, NA, NA),
#        lwd=c(2, NA, NA, NA, NA), pch=c(NA, 19, 17, 15, 18))
legend("topleft", c("Model, whole body", "Data, blood", "Data, subcutaneous fat",
                    "Data, perirenal fat"),
       col=vcol[1:4], lty=c(1, NA, NA, NA),
       lwd=c(2, NA, NA, NA), pch=c(NA, 19, 17, 15))
dev.off()


# Plot filial animal concentrations vs. time from model along with data.
# C_i_nmol_per_kg = out[, "C_i"] * (1e6) / MW  # Model estimates (nmol/kg).
C_i_nmol_per_kg = C_i_med * (1e6) / MW
C_i_nmol_per_kg_lo = C_i_lo * (1e6) / MW
C_i_nmol_per_kg_hi = C_i_hi * (1e6) / MW
C_i_blood = c(NA, 27.9)          # Blood data (nmol/L).
C_i_blood_sd = c(NA, 2.10)
C_i_subcfat = c(NA, 1495)        # Subcutaneous fat data (pmol/g).
C_i_subcfat_sd = c(NA, 240)
C_i_perifat = c(NA, 2351)        # Perirenal fat data (pmol/g).
C_i_perifat_sd = c(NA, 238)
C_i_whole = c(22.72, NA)
C_i_whole_sd = c(4.34, NA)
t_data = c(21, 38)               # Days since conception.

file_name = "./Output/nakashima1997_exp1_filial_concentration_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, C_i_nmol_per_kg, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (pmol/g)",
     ylim=c(0, 2600))
lines(times, C_i_nmol_per_kg_lo, lty=2, lwd=2, col=vcol[1])
lines(times, C_i_nmol_per_kg_hi, lty=2, lwd=2, col=vcol[1])
points(t_data, C_i_blood, pch=19, col=vcol[2], cex=1.0)
arrows(t_data, C_i_blood-C_i_blood_sd, t_data, C_i_blood+C_i_blood_sd, code=3,
       angle=90, length=0.05, lwd=2, col=vcol[2])
points(t_data, C_i_subcfat, pch=17, col=vcol[3], cex=1.0)
arrows(t_data, C_i_subcfat-C_i_subcfat_sd, t_data, C_i_subcfat+C_i_subcfat_sd,
       code=3, angle=90, length=0.05, lwd=2, col=vcol[3])
points(t_data, C_i_perifat, pch=15, col=vcol[4], cex=1.0)
arrows(t_data, C_i_perifat-C_i_perifat_sd, t_data, C_i_perifat+C_i_perifat_sd,
       code=3, angle=90, length=0.05, lwd=2, col=vcol[4])
points(t_data, C_i_whole, pch=18, col=vcol[5], cex=1.0)
arrows(t_data, C_i_whole-C_i_whole_sd, t_data, C_i_whole+C_i_whole_sd,
       code=3, angle=90, length=0.05, lwd=2, col=vcol[5])
legend("topleft", c("Model, whole body", "Data, blood",
                    "Data, subcutaneous fat", "Data, perirenal fat",
                    "Data, whole body"),
       col=vcol[1:5], lty=c(1, NA, NA, NA, NA),
       lwd=c(2, NA, NA, NA, NA), pch=c(NA, 19, 17, 15, 18))
dev.off()

# Compare estimated and observed whole-body concentrations.
term_idx = match(21, out[, "time"])
cat("Estimated (median) whole body concentration at 21 d:",
    C_i_nmol_per_kg[term_idx], "nmol/kg\n")
cat("Estimated (lower 95% CI bound) whole body concentration at 21 d:",
    C_i_nmol_per_kg_lo[term_idx], "nmol/kg\n")
cat("Observed whole body concentration at 21 d:",
    C_i_whole[1], "nmol/kg\n")

# Plot total cumulative amount of HCB that has entered the dam. Convert mg to
# nmol.
# T_in_nmol = out[, "T_in"] * 1000.0 / MW  # Model estimates (nmol).
T_in_nmol = out[, "T_in"] * (1e6) / MW  # Model estimates (nmol).

file_name = "./Output/nakashima1997_exp1_amount_in_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, T_in_nmol, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Cumulative Input (nmol)",
     ylim=c(0, 250))
points(c(21), c(120*0.9), pch=18, col="black", cex=1.0)
dev.off()
