#------------------------------------------------------------------------------
# hed_vodicnik1980.R
#
# This code computes a human equivalent dose using the model "lipophilic_tk" 
# for mice exposed to PCB 153 in the study of Vodicnik and Lech (1980).
#
# Author: Dustin Kapraun, US EPA, December 2020
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")

# Nominal dose (mg/kg or ug/g) from Vodicnik and Lech (1980).
d_m_calc = 50

# Initial amount (bolus dose) in mother based on default initial mass of 0.0255
# kg.
p = init_mouse_p()
A_m_init = d_m_calc * p[["M_m_1"]]

# Define simulation parameters (median half-life)
p <- c(t_lact = 20,        # Duration of lactation/breastfeeding (d).
       t_gest = 21,        # Duration of gestation (d).
       # half_life = 50.3,   # Half-life (d) from T. Zurlinden model.
       # half_life = 52.7,   # Half-life (d) from T. Zurlinden model.
       # half_life = 37.5,   # Half-life (d) from 9/28/2021 analysis.
       # half_life = 37.7,   # Half-life (d) from 10/6/2021 analysis.
       half_life = 38.5,   # Half-life (d) from 1/3/2022 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       t_m_start = -2 * 7, # Start time (d) of dosing/experiment.
       A_m_init = A_m_init)   # Initial amount (mg) in mother.

p = init_mouse_p(p)

# Simulation times of interest.
t_start = - 2 * 7
t_obs = p[["t_gest"]] + p[["t_lact"]]
p[["t_m_end"]] = t_obs
p[["t_i_end"]] = t_obs
times = seq(from=t_start, to=t_obs, by=0.1)

# Recalculate any parameters that depend on other parameters!
p = init_mouse_p(p)

# Run simulation.
out <- mouse_sim(times=times, p=p)

# # Plot maternal animal concentration and data vs. time.
# C_m_data = c(15.12, 8.59, 3.48, 0.87, 0.37)  # ug/g or mg/kg
# t_data = p[["t_gest"]] + c(5, 10, 15, 20)    # d
# t_data = c(19, t_data)
# plot(times, out[, "C_m"], type='l', lwd=2, col=vcol[1],
#      xlab="Time Since Conception (d)",
#      ylab="Maternal Animal Concentration (mg/kg)",
#      ylim=c(0, 50))
# points(t_data, C_m_data, pch=19, col=vcol[2], cex=1.0)

# Plot filial animal concentration vs. time.
C_i_data = c(15.31, 13.97, 11.18, 12.50)   # ug/g or mg/kg
t_data = p[["t_gest"]] + c(5, 10, 15, 20)  # d
plot(times, out[, "C_i"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (mg/kg)",
     ylim=c(0, 18))
points(t_data, C_i_data, pch=19, col=vcol[2], cex=1.0)

# Compute each dose metric and the corresponding human equivalent dose (HED).
DM_vec = rep(NA, 5)
HED_vec = rep(NA, 5)
DM_human_vec = rep(NA, 5)
human_age = 365        # Final age (d) for filial human.
human_HL = 14.4 * 365  # Half-life (d) in humans. Half-life of PCB 153 in
                       #  humans is 14.4 y (Ritter et al., 2011).
for (DM in seq(5)) {
    DM_vec[DM] = comp_dose_metric(times, out[, "C_i"], out[, "AUC_i"],
                                  p[["t_gest"]], p[["t_lact"]], DM)
    HED_vec[DM] = comp_hed(DM, DM_vec[DM], human_age=human_age,
                           human_HL=human_HL)

    # Run simulation of human exposure at HED.
    p_human = c(d_m=HED_vec[DM], half_life=human_HL)
    p_human = init_human_p(p_human)
    if (DM < 5) {
        times_human=NULL
    } else {
        if (is.null(human_age)) {
            t_end = 78.75 * 365              # Lifetime of filial human (d),
        }                                    #  including time in-utero.
        else {
            t_end = human_age + 0.75 * 365   # Lifetime of filial human (d),
        }                                    #  including time in-utero.
        t_start = -24.25 * 365               # Birth of mother (d).
        times_human = seq(from=t_start, to=t_end, by=0.25)
    }
    out_human <- human_sim(times=times_human, p=p_human, preg=TRUE)

    # Compute human dose metric.
    DM_human = comp_dose_metric(out_human[ , "time"], out_human[ , "C_i"],
                                out_human[ , "AUC_i"],
                                p_human[["t_gest"]], p_human[["t_lact"]], DM)
    DM_human_vec[DM] = DM_human
}

# Create a dataframe to hold HED information
hed_df = cbind(DM_vec, HED_vec, DM_human_vec)
colnames(hed_df) = c("Animal Dose Metric", "Human Equivalent Dose",
                     "Human Dose Metric")
rownames(hed_df) = seq(length(DM_vec))

# Print HED information.
print(hed_df)
