#------------------------------------------------------------------------------
# hed_nakashima1997.R
#
# This code computes a human equivalent dose using the model "lipophilic_tk" 
# for rats exposed to hexachlorobenzene (HCB) in the study of Nakashima et al.
# (1997).
#
# Author: Dustin Kapraun, US EPA, December 2020
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")

# Initialize parameters with values used for Nakashima et al. (1997) study.
# Calculate dose (mg/kg) from nominal dose 35.1 nmol per 100 g of diet.
MW = 284.8    # Molecular weight (g/mol or ng/nmol).
d_m_calc = 35.1 * MW / (10 ** 5)

# Effective number of fetuses should yield sufficient weight loss to take the
# dam from her late-term mass to her post-natal (PND 16) body mass.
n_f_calc = (0.3905 - 0.247) / 0.0066

# Effective number of infants should be the average number of suckling pups for
# the dams in the study
n_i_calc = mean(c(15, 14, 14))

# Define simulation parameters.
p <- c(t_lact = 16,        # Duration (d) of lactation/nursing. Set to PND 16.
       M_m_1 = 0.247,      # Maternal mass 1 (kg).
       M_m_2 = 0.3905,     # Maternal mass 2 (kg).
       t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
       t_m_2 = 21,         # Time (d) since conception for maternal mass 2.
       M_i_3 = 0.0286,     # Infant mass 3 (kg).
       t_i_3 = 16,         # Time (d) since birth for infant mass 3.
       n_f = n_f_calc,     # Effective number of fetuses.
       n_i = n_i_calc,     # Number of infants.
       # half_life = 104,    # Half-life (d) from T. Zurlinden model.
       # half_life = 76.1,   # Half-life (d) from T. Zurlinden model.
       # half_life = 94.2,   # Half-life (d) from T. Zurlinden model.
       half_life = 92.4,   # Half-life (d)  based on 10/6/2021 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       F_m = 0.094,        # Fraction of maternal mass that is fat.
       F_abs = 0.56,       # Fraction of nominal dose that is absorbed.
       food_dose = 1,      # A boolean flag. Dose is delivered in food if
                           #   nonzero.
       d_m = d_m_calc,     # Dose rate (mg/kg/d or mg/kg) to mother.
       t_m_start = 0,      # Time (d) since conception maternal dose starts.
       t_m_end = 38)       # Time (d) since conception maternal dose ends.

p = init_rat_p(p)

# Times for simulation.
t_obs = p[["t_gest"]] + p[["t_lact"]]
p[["t_m_end"]] = t_obs
p[["t_i_end"]] = t_obs
times = seq(from=0, to=t_obs, by=0.1)

# Recalculate any parameters that depend on other parameters!
p = init_rat_p(p)

# Run simulation.
out = rat_sim(times, p)

# # Plot maternal animal concentrations vs. time from model along with data.
# C_m_nmol_per_kg = out[, "C_m"] * (1e6) / MW   # Model estimates (nmol/kg).
# C_m_blood = c((12.01+15.48)/2, 3.84)          # Blood data (nmol/L).
# C_m_subcfat = c((546.2+909.5)/2, 49.10)       # Subcutaneous fat data (pmol/g).
# C_m_perifat = c((445.6 + 358.2)/2, 145.9)     # Perirenal fat data (pmol/g).
# C_m_whole = c(145.7, 27.0)
# t_data = c(21, 38)                            # Days since conception.
# plot(out[, "time"], C_m_nmol_per_kg, type='l', lwd=2, col=vcol[1],
#      xlab="Time Since Conception (d)",
#      ylab="Maternal Animal Concentration (pmol/g)",
#      ylim=c(0, 750))
# points(t_data, C_m_blood, pch=19, col=vcol[2], cex=1.0)
# points(t_data, C_m_subcfat, pch=17, col=vcol[3], cex=1.0)
# points(t_data, C_m_perifat, pch=15, col=vcol[4], cex=1.0)
# legend("topleft", c("Model, whole body", "Data, blood", "Data, subcutaneous fat",
#                     "Data, perirenal fat"),
#        col=vcol[1:4], lty=c(1, NA, NA, NA),
#        lwd=c(2, NA, NA, NA), pch=c(NA, 19, 17, 15))
# 
# # Plot filial animal concentrations vs. time from model along with data.
# C_i_nmol_per_kg = out[, "C_i"] * (1e6) / MW  # Model estimates (nmol/kg).
# C_i_blood = c(NA, 27.9)          # Blood data (nmol/L).
# C_i_subcfat = c(NA, 1495)        # Subcutaneous fat data (pmol/g).
# C_i_perifat = c(NA, 2351)        # Perirenal fat data (pmol/g).
# # C_i_whole = c(22.72, (27.90 + 1495 + 2351)/3) # Whole body concentration (pmol/g).
# C_i_whole = c(22.72, 276.6)
# t_data = c(21, 38)                            # Days since conception.
# plot(out[, "time"], C_i_nmol_per_kg, type='l', lwd=2, col=vcol[1],
#      xlab="Time Since Conception (d)",
#      ylab="Filial Animal Concentration (pmol/g)",
#      ylim=c(0, 2500))
# points(t_data, C_i_blood, pch=19, col=vcol[2], cex=1.0)
# points(t_data, C_i_subcfat, pch=17, col=vcol[3], cex=1.0)
# points(t_data, C_i_perifat, pch=15, col=vcol[4], cex=1.0)
# points(t_data[1], C_i_whole[1], pch=18, col=vcol[5], cex=1.0)
# # points(t_data[2], C_i_whole[2], pch=18, col="black", cex=1.0)
# legend("topleft", c("Model, whole body", "Data, blood",
#                     "Data, subcutaneous fat", "Data, perirenal fat",
#                     "Data, whole body"),
#        col=vcol[1:5], lty=c(1, NA, NA, NA, NA),
#        lwd=c(2, NA, NA, NA, NA), pch=c(NA, 19, 17, 15, 18))

# Plot filial animal concentration (mg/kg) vs. time.
plot(times, out[, "C_i"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (mg/kg)")

# Compute each dose metric and the corresponding human equivalent dose (HED).
DM_vec = rep(NA, 5)
HED_vec = rep(NA, 5)
DM_human_vec = rep(NA, 5)
human_age = 365     # Final age (d) for filial human.
human_HL = 6 * 365  # Half-life (d) in humans. Half-life of HCB in humans is
                    #  6 y (To-Figueras, 2000).
for (DM in seq(5)) {
    DM_vec[DM] = comp_dose_metric(times, out[, "C_i"], out[, "AUC_i"],
                                  p[["t_gest"]], p[["t_lact"]], DM)
    HED_vec[DM] = comp_hed(DM, DM_vec[DM], human_age=human_age,
                           human_HL=human_HL)
    
    # Run simulation of human exposure at HED.
    p_human = c(d_m=HED_vec[DM], half_life=human_HL)
    p_human = init_human_p(p_human)
    if (DM < 5) {
        times_human=NULL
    } else {
        if (is.null(human_age)) {
            t_end = 78.75 * 365              # Lifetime of filial human (d),
        }                                    #  including time in-utero.
        else {
            t_end = human_age + 0.75 * 365   # Lifetime of filial human (d),
        }                                    #  including time in-utero.
        t_start = -24.25 * 365               # Birth of mother (d).
        times_human = seq(from=t_start, to=t_end, by=0.25)
    }
    out_human <- human_sim(times=times_human, p=p_human, preg=TRUE)

    # Compute human dose metric.
    DM_human = comp_dose_metric(out_human[ , "time"], out_human[ , "C_i"],
                                out_human[ , "AUC_i"],
                                p_human[["t_gest"]], p_human[["t_lact"]], DM)
    DM_human_vec[DM] = DM_human
}

# Create a dataframe to hold HED information
hed_df = cbind(DM_vec, HED_vec, DM_human_vec)
colnames(hed_df) = c("Animal Dose Metric", "Human Equivalent Dose",
                     "Human Dose Metric")
rownames(hed_df) = seq(length(DM_vec))

# Print HED information.
print(hed_df)
