#------------------------------------------------------------------------------
# pcb153_vodicnik1980_study2_mc.R
#
# This file runs simulations of the Vodicnik and Lech (1980) study 2 of PCB 153
# mice (dams and pups). Briefly, dams were dosed once with radio-labeled PCB
# 153 before mating. Two animals were sacrificed on Day 19 of pregnancy
# (gestation 20 to 21 days), and two mothers and their litters were sacrificed
# at 5, 10, 15, and 20 days postpartum and total carcass content determined.
#
# Author: Dustin Kapraun, U.S. EPA, March 2022
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
#script.dir = dirname(sys.frame(1)$ofile)
#setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")

# Nominal dose (mg/kg or ug/g) from Vodicnik and Lech (1980).
d_m_calc = 50

# Initial amount (bolus dose) in mother based on default initial mass of 0.0255
# kg.
p = init_mouse_p()
A_m_init = d_m_calc * p[["M_m_1"]]

# Define simulation parameters (median half-life)
p <- c(t_gest = 21,        # Duration of gestation (d).
       # half_life = 50.3,   # Half-life (d) from T. Zurlinden model.
       # half_life = 52.7,   # Half-life (d) from T. Zurlinden model.
       # half_life = 37.5,   # Half-life (d) from T. Zurlinden model.
       # half_life = 36.2,   # Half-life (d) from 9/28/2021 analysis.
       # half_life = 37.7,   # Half-life (d) from 10/6/2021 analysis.
       half_life = 38.5,   # Half-life (d) from 1/3/2022 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       t_m_start = -2 * 7, # Start time (d) of dosing/experiment.
       A_m_init = A_m_init)   # Initial amount (mg) in mother.

p = init_mouse_p(p)
t_start = - 2 * 7
t_obs = p[["t_gest"]] + 20
times = seq(from=t_start, to=t_obs, by=0.1)

# Run simulation.
out <- mouse_sim(times=times, p=p)


# Specify number of Monte Carlo simulations.
N_MC = 1000

# Create empty arrays to store simulation results.
C_m_MC = array(numeric(), c(length(times), N_MC))
C_i_MC = array(numeric(), c(length(times), N_MC))

# Seed random number generator.
set.seed(2022)

# Generate random values for influential parameters.
F_milk_MC = rnorm(N_MC, mean=0.264, sd=0.3*0.264)
F_m_MC = rnorm(N_MC, mean=0.229, sd=0.3*0.229)
r_f_m_MC = rnorm(N_MC, mean=0.35, sd=0.3*0.35)
# half_life_MC = rnorm(N_MC, mean=38.5, sd=7.5)
half_life_df = read.csv("posterior_halft_PCB153.csv")
rand_idx = sample.int(N_MC, size=nrow(half_life_df), replace=TRUE)
half_life_MC = half_life_df[rand_idx, 2]


for (idx in seq(N_MC)) {
    # Define simulation parameters
    p <- c(half_life = half_life_MC[idx],
           r_f_m = r_f_m_MC[idx],
           F_m = F_m_MC[idx],
           F_milk = F_milk_MC[idx],
           t_m_start = -2 * 7, # Start time (d) of dosing/experiment.
           A_m_init = A_m_init)   # Initial amount (mg) in mother.    
    p = init_mouse_p(p)
    
    # Run simulation.
    out_MC <- mouse_sim(times=times, p=p)
    
    # Save results.
    C_m_MC[ , idx] = out_MC[ , "C_m"]
    C_i_MC[ , idx] = out_MC[ , "C_i"]
}

# Find credible intervals for concentrations.
conf = 0.95
alpha = 1 - conf
lo = alpha / 2
hi = 1 - lo
C_m_lo = apply(C_m_MC, 1, quantile, probs=lo)
C_m_hi = apply(C_m_MC, 1, quantile, probs=hi)
C_m_med = apply(C_m_MC, 1, quantile, probs=0.5)
C_i_lo = apply(C_i_MC, 1, quantile, probs=lo)
C_i_hi = apply(C_i_MC, 1, quantile, probs=hi)
C_i_med = apply(C_i_MC, 1, quantile, probs=0.5)



# Data.
C_m_data = c(15.12, 8.59, 3.48, 0.87, 0.37)  # ug/g or mg/kg
t_data = p[["t_gest"]] + c(5, 10, 15, 20)    # d
t_data = c(19, t_data)



# Plot maternal animal concentration and data vs. time and write to file.
file_name = "./Output/vodicnik1980_maternal_concentration_mc.tif"

tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, C_m_med, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Maternal Animal Concentration (mg/kg)",
     ylim=c(0, 50))
lines(times, C_m_lo, lty=2, lwd=2, col=vcol[1])
lines(times, C_m_hi, lty=2, lwd=2, col=vcol[1])
points(t_data, C_m_data, pch=19, col=vcol[2], cex=1.0)
dev.off()

# Compare estimated and observed whole-body concentrations in dams.
t_data_idx = match(t_data, out[, "time"])
# C_m_est = out[t_data_idx, "C_m"]
C_m_est = C_m_med[t_data_idx]
cat("Maternal whole body concentrations...\n")
for (idx in seq(length(t_data_idx))) {
        cat("  Estimated concentration at ",  t_data[idx], " d: ",
            C_m_est[idx], " nmol/kg\n", sep="")
        cat("  Observed concentration at ", t_data[idx], " d:  ",
            C_m_data[idx], " nmol/kg\n", sep="")
}
perc_diff = 200 * abs(C_m_data - C_m_est) / abs(C_m_data + C_m_est)
cat("  Maximum percent difference: ", max(perc_diff), "%.\n", sep="")



# Data.
C_i_data = c(15.31, 13.97, 11.18, 12.50)   # ug/g or mg/kg
t_data = p[["t_gest"]] + c(5, 10, 15, 20)  # d


# Plot filial animal concentration vs. time and write to file.
file_name = "./Output/vodicnik1980_filial_concentration_mc.tif"
tiff(file_name, units="in", width=6, height=5, res=300)
plot(times, C_i_med, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (mg/kg)",
     ylim=c(0, 23))
lines(times, C_i_lo, lty=2, lwd=2, col=vcol[1])
lines(times, C_i_hi, lty=2, lwd=2, col=vcol[1])
points(t_data, C_i_data, pch=19, col=vcol[2], cex=1.0)
dev.off()


# Compare estimated and observed whole-body concentrations in offspring.
t_data_idx = match(t_data, out[, "time"])
# C_i_est = out[t_data_idx, "C_i"]
C_i_est = C_i_med[t_data_idx]
cat("Filial whole body concentrations...\n")
for (idx in seq(length(t_data_idx))) {
  cat("  Estimated whole body concentration at ",  t_data[idx], " d: ",
      C_i_est[idx], " nmol/kg\n", sep="")
  cat("  Observed whole body concentration at ", t_data[idx], " d:  ",
      C_i_data[idx], " nmol/kg\n", sep="")
}
perc_diff = 200 * abs(C_i_data - C_i_est) / abs(C_i_data + C_i_est)
cat("  Maximum percent difference: ", max(perc_diff), "%.\n", sep="")
