#------------------------------------------------------------------------------
# sensitivity_analysis_vodicnik.R
#
# This code performs a local sensitivity analysis for the model
# "lipophilic_tk". The sensitivities are calculated based on perturbations
# about a set of parameter values selected for mice exposed to PCB 153 in the
# study of Vodicnik and Lech (1980).
#
# Author: Dustin Kapraun, US EPA, November 2020
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")


# Define a function to run model simulations based on a parameter vector q.
run_sim <- function(q) {
    # Run a simulation that corresponds to the conditions of the Vodicnik and
    # Lech (1980) study.
    
    # Simulation times of interest.
    t_start = q[["t_m_start"]]
    t_obs = q[["t_gest"]] + q[["t_lact"]]
    q[["t_m_end"]] = t_obs
    q[["t_i_end"]] = t_obs
    times = seq(from=t_start, to=t_obs, by=0.1)
    
    # Ensure that the times corresponding to conception, birth, weaning, and
    # start and stop of dosing are included.
    times = unique(c(times, 0, q[["t_gest"]], q[["t_gest"]] + q[["t_lact"]],
                     q[["t_m_start"]], q[["t_m_end"]], q[["t_i_start"]],
                     q[["t_i_end"]]))
    times = times[order(times)]
    
    # Recalculate any parameters that depend on other parameters!
    q = init_mouse_p(q)
    
    # Run simulation.
    out = mouse_sim(times, q)
    
    # Return simulation output.
    return(out)
}


comp_sens <- function(q, rel_step=1.0e-2) {
    # Ensure rel_step is positive.
    rel_step = abs(rel_step)

    # Run a simulation for the parameter values in q.
    out_q = run_sim(q)

    # Compute values of the five dose metrics for values in q.
    times = out_q[ , "time"]
    DM1_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 1)
    DM2_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 2)
    DM3_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 3)
    DM4_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 4)
    DM5_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 5)
    

    # Create a dataframe to store sensitivity indices.
    len_q = length(q)
    sens_df = data.frame(param_val=q,
                         DM1=double(len_q),
                         DM2=double(len_q),
                         DM3=double(len_q),
                         DM4=double(len_q),
                         DM5=double(len_q))

    # For each parameter in q, compute local sensitivity indices for all five
    # dose metrics.
    for (qname in names(q)) {
        # Perturb this parameter by the "rel_step" amount.
        qx = q
        if (is.nan(q[qname])) {
            next
        } else if (abs(q[qname]) >= rel_step / (1 + rel_step)) {
            qx[qname] = q[qname] * (1 + rel_step)
        } else if (q[qname] >= 0) {
            qx[qname] = rel_step
        } else {
            qx[qname] = -rel_step
        }

        # Run a simulation
        out_qx = run_sim(qx)

        # Compute values of the five dose metrics for values in q.
        times = out_qx[ , "time"]
        DM1_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 1)
        DM2_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 2)
        DM3_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 3)
        DM4_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 4)
        DM5_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 5)
        
        # Compute sensitivity indices for each dose metric.
        sens_df[qname, "DM1"] = (DM1_qx - DM1_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM1_q)
        sens_df[qname, "DM2"] = (DM2_qx - DM2_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM2_q)
        sens_df[qname, "DM3"] = (DM3_qx - DM3_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM3_q)
        sens_df[qname, "DM4"] = (DM4_qx - DM4_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM4_q)
        sens_df[qname, "DM5"] = (DM5_qx - DM5_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM5_q)
    }

    # Return the dataframe containing the sensitivity analysis results.
    return(sens_df)
}


# Nominal dose (mg/kg or ug/g) from Vodicnik and Lech (1980).
d_m_calc = 50

# Initial amount (bolus dose) in mother based on default initial mass of 0.0255
# kg.
p = init_mouse_p()
A_m_init = d_m_calc * p[["M_m_1"]]

# Define simulation parameters (median half-life)
p <- c(t_lact = 20,        # Duration of lactation/breastfeeding (d).
       t_gest = 21,        # Duration of gestation (d).
       # half_life = 50.3,   # Half-life (d) from T. Zurlinden model.
       # half_life = 52.7,   # Half-life (d) from T. Zurlinden model.
       # half_life = 37.5,   # Half-life (d) from 9/28/2021 analysis.
       # half_life = 37.7,   # Half-life (d) from 10/6/2021 analysis.
       half_life = 38.5,   # Half-life (d) from 1/3/2022 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       t_m_start = -14,    # Start time (d) of dosing/experiment.
       A_m_init = A_m_init)   # Initial amount (mg) in mother.

p = init_mouse_p(p)

# Run simulation.
out <- run_sim(p)

# Plot maternal animal concentration and data vs. time.
C_m_data = c(15.12, 8.59, 3.48, 0.87, 0.37)  # ug/g or mg/kg
t_data = p[["t_gest"]] + c(5, 10, 15, 20)    # d
t_data = c(19, t_data)
plot(out[, "time"], out[, "C_m"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Maternal Animal Concentration (mg/kg)",
     ylim=c(0, 50))
points(t_data, C_m_data, pch=19, col=vcol[2], cex=1.0)

# Plot filial animal concentration vs. time.
C_i_data = c(15.31, 13.97, 11.18, 12.50)   # ug/g or mg/kg
t_data = p[["t_gest"]] + c(5, 10, 15, 20)  # d
plot(out[, "time"], out[, "C_i"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (mg/kg)",
     ylim=c(0, 16))
points(t_data, C_i_data, pch=19, col=vcol[2], cex=1.0)

# Perform sensitivity analysis.
sens_df = comp_sens(p)

# Write sensitivity indices to a CSV file.
file_name = "./Output/sens_vodicnik1980.csv"
write.csv(sens_df, file_name)

# Remove rows corresponding to unused parameters.
sens_df = sens_df[!is.nan(sens_df[["param_val"]]), ]

# Find all parameters (rows in the data frame) for which at least one of the
# normalized sensitivity indices is greater than 0.2.
sens_df_red = sens_df[rowSums(abs(sens_df[ , 2:ncol(sens_df)]) > 0.25) > 0,
                      2:ncol(sens_df)]

# Remove the parameters t_m_end and t_i_end from consideration. They have been
# set to coincide with the end of lactation, so sensitivity can be observed for
# just t_lact.
# sens_df_red = sens_df_red[row.names(sens_df_red) != "t_m_end", ]
# sens_df_red = sens_df_red[row.names(sens_df_red) != "t_i_end", ]

# Sort the rows based on values of DM1.
sens_df_red = sens_df_red[order(sens_df_red["DM1"]), ]

# Plot normalized sensitivity indices for DM1.
S1_vec = as.vector(sens_df[["DM1"]])
names(S1_vec) = row.names(sens_df)
S1_vec = S1_vec[order(-abs(S1_vec))]
plot(S1_vec)

S1_vec = as.vector(sens_df_red[["DM1"]])
names(S1_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM1_vodicnik1980.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S1_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM1")
dev.off()

# Plot normalized sensitivity indices for difference between average blood
# concentration and baseline blood concentration.
S2_vec = as.vector(sens_df[["DM2"]])
names(S2_vec) = row.names(sens_df)
S2_vec = S2_vec[order(-abs(S2_vec))]
plot(S2_vec)

S2_vec = as.vector(sens_df_red[["DM2"]])
names(S2_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM2_vodicnik1980.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S2_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM2")
dev.off()

# Plot normalized sensitivity indices for peak blood concentration.
S3_vec = as.vector(sens_df[["DM3"]])
names(S3_vec) = row.names(sens_df)
S3_vec = S3_vec[order(-abs(S3_vec))]
plot(S3_vec)

S3_vec = as.vector(sens_df_red[["DM3"]])
names(S3_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM3_vodicnik1980.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S3_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM3")
dev.off()

# Plot normalized sensitivity indices for difference between peak blood
# concentration and baseline blood concentration.
S4_vec = as.vector(sens_df[["DM4"]])
names(S4_vec) = row.names(sens_df)
S4_vec = S4_vec[order(-abs(S4_vec))]
plot(S4_vec)

S4_vec = as.vector(sens_df_red[["DM4"]])
names(S4_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM4_vodicnik1980.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S4_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM4")
dev.off()

# Plot normalized sensitivity indices for DM1 through DM4, all side-by-side.
file_name = "./Output/sens_all_vodicnik1980.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(t(as.matrix(sens_df_red[c(4, 3, 2, 1)])), horiz=TRUE,
        col=vcol[c(4, 3, 2, 1)],
        border=NA, beside=TRUE, las=2, xlim=c(-1.0, 1.0),
        xlab="Normalized Local Sensitivity Index")
legend("bottomright", legend=c("Dose Metric 1", "Dose Metric 2",
                               "Dose Metric 3", "Dose Metric 4"),
       fill=vcol[c(1, 2, 3, 4)], border=NA, box.lty=1, cex=0.9)
dev.off()