#------------------------------------------------------------------------------
# sensitivity_analysis_human.R
#
# This code performs a local sensitivity analysis for the model
# "lipophilic_tk". The sensitivities are calculated based on perturbations
# about a set of parameter values selected for human simulations of exposure
# scenarios for HCB. Simulations are for a human mother and offspring from the
# birth of the mother until the offspring reaches age 1 year (when the mother
# reaches age 26 y). The substance is assumed to have a half-life of 2190 days
# (the estimated human elimination half-life for HCB).
#
# Author: Dustin Kapraun, US EPA, September 2021
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
#I'm commenting the lines below.'
#script.dir = dirname(sys.frame(1)$ofile)
#setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")


# Define a function to run model simulations based on a parameter vector q.
run_sim <- function(q) {
    # Run a simulation that corresponds to a simulation of a human mother and
    # her offspring exposed to a lipophilic substance.
    out = human_sim(times=NULL, p=q)
    
    # Return simulation output.
    return(out)
}


comp_sens <- function(q, rel_step=1.0e-2) {
    # Ensure rel_step is positive.
    rel_step = abs(rel_step)

    # Run a simulation for the parameter values in q.
    out_q = run_sim(q)
    
    # Obtain values of "t_gest" and "t_lact".
    p = init_human_p(q)
    t_gest = p[["t_gest"]]
    t_lact = p[["t_lact"]]

    # Compute values of the five dose metrics for values in q.
    times = out_q[ , "time"]
    DM1_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             t_gest, t_lact, 1)
    DM2_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             t_gest, t_lact, 2)
    DM3_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             t_gest, t_lact, 3)
    DM4_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             t_gest, t_lact, 4)
    DM5_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             t_gest, t_lact, 5)
    

    # Create a dataframe to store sensitivity indices.
    len_q = length(q)
    sens_df = data.frame(param_val=q,
                         DM1=double(len_q),
                         DM2=double(len_q),
                         DM3=double(len_q),
                         DM4=double(len_q),
                         DM5=double(len_q))

    # For each parameter in q, compute local sensitivity indices for all five
    # dose metrics.
    for (qname in names(q)) {
        # Perturb this parameter by the "rel_step" amount.
        qx = q
        if (is.nan(q[qname])) {
            next
        } else if (abs(q[qname]) >= rel_step / (1 + rel_step)) {
            qx[qname] = q[qname] * (1 + rel_step)
        } else if (q[qname] >= 0) {
            qx[qname] = rel_step
        } else {
            qx[qname] = -rel_step
        }

        # Run a simulation
        out_qx = run_sim(qx)
        
        # Obtain values of "t_gest" and "t_lact".
        px = init_human_p(qx)
        t_gest = px[["t_gest"]]
        t_lact = px[["t_lact"]]

        # Compute values of the five dose metrics for values in q.
        times = out_qx[ , "time"]
        DM1_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  t_gest, t_lact, 1)
        DM2_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  t_gest, t_lact, 2)
        DM3_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  t_gest, t_lact, 3)
        DM4_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  t_gest, t_lact, 4)
        DM5_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  t_gest, t_lact, 5)
        
        # Compute sensitivity indices for each dose metric.
        sens_df[qname, "DM1"] = (DM1_qx - DM1_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM1_q)
        sens_df[qname, "DM2"] = (DM2_qx - DM2_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM2_q)
        sens_df[qname, "DM3"] = (DM3_qx - DM3_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM3_q)
        sens_df[qname, "DM4"] = (DM4_qx - DM4_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM4_q)
        sens_df[qname, "DM5"] = (DM5_qx - DM5_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM5_q)
    }

    # Return the dataframe containing the sensitivity analysis results.
    return(sens_df)
}

# Define simulation parameters.
q <- c(half_life = 2190,     # Half-life (d) of substance in this species.
       F_m = 0.346,          # Fraction of maternal mass that is fat.
       F_milk = 0.039,       # Fraction of breast milk that is fat.
       r_f_m = 0.5,          # Ratio of fetal and maternal concentrations.
       F_abs = 0.9,          # Fraction of nominal dose that is absorbed.
       d_m = 1,              # Dose rate (mg/kg/d or mg/kg) to mother.
       A_m_init = 0)         # Initial amount (mg) in mother.

# Run simulation.
out <- run_sim(q)

# Plot maternal animal concentration and data vs. time.
plot(out[, "time"], out[, "C_m"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Maternal Animal Concentration (mg/kg)")

# Plot filial animal concentration vs. time.
plot(out[, "time"], out[, "C_i"], type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (mg/kg)")

# Perform sensitivity analysis.
sens_df = comp_sens(q)

# Write sensitivity indices to a CSV file.
file_name = "./Output/sens_human.csv"
write.csv(sens_df, file_name)

# Remove rows corresponding to unused parameters.
sens_df = sens_df[!is.nan(sens_df[["param_val"]]), ]

# Find all parameters (rows in the data frame) for which at least one of the
# normalized sensitivity indices is greater than 0.2.
sens_df_red = sens_df[rowSums(abs(sens_df[ , 2:ncol(sens_df)]) > 0.2) > 0,
                      2:ncol(sens_df)]

# Sort the rows based on values of DM1.
sens_df_red = sens_df_red[order(sens_df_red["DM1"]), ]

# Plot normalized sensitivity indices for DM1.
S1_vec = as.vector(sens_df[["DM1"]])
names(S1_vec) = row.names(sens_df)
S1_vec = S1_vec[order(-abs(S1_vec))]
plot(S1_vec)

S1_vec = as.vector(sens_df_red[["DM1"]])
names(S1_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM1_human.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S1_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM1")
dev.off()

# Plot normalized sensitivity indices for difference between average blood
# concentration and baseline blood concentration.
S2_vec = as.vector(sens_df[["DM2"]])
names(S2_vec) = row.names(sens_df)
S2_vec = S2_vec[order(-abs(S2_vec))]
plot(S2_vec)

S2_vec = as.vector(sens_df_red[["DM2"]])
names(S2_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM2_human.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S2_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM2")
dev.off()

# Plot normalized sensitivity indices for peak blood concentration.
S3_vec = as.vector(sens_df[["DM3"]])
names(S3_vec) = row.names(sens_df)
S3_vec = S3_vec[order(-abs(S3_vec))]
plot(S3_vec)

S3_vec = as.vector(sens_df_red[["DM3"]])
names(S3_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM3_human.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S3_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM3")
dev.off()

# Plot normalized sensitivity indices for difference between peak blood
# concentration and baseline blood concentration.
S4_vec = as.vector(sens_df[["DM4"]])
names(S4_vec) = row.names(sens_df)
S4_vec = S4_vec[order(-abs(S4_vec))]
plot(S4_vec)

S4_vec = as.vector(sens_df_red[["DM4"]])
names(S4_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM4_human.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S4_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM4")
dev.off()

# Plot normalized sensitivity indices for DM1 through DM4, all side-by-side.
file_name = "./Output/sens_all_human.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(t(as.matrix(sens_df_red[c(4, 3, 2, 1)])), horiz=TRUE,
        col=vcol[c(4, 3, 2, 1)],
        border=NA, beside=TRUE, las=2, xlim=c(-1.0, 1.0),
        xlab="Normalized Local Sensitivity Index")
legend("bottomright", legend=c("Dose Metric 1", "Dose Metric 2",
                               "Dose Metric 3", "Dose Metric 4"),
       fill=vcol[c(1, 2, 3, 4)], border=NA, box.lty=1, cex=0.9)
dev.off()