#------------------------------------------------------------------------------
# sensitivity_analysis_nakashima1997.R
#
# This code performs a local sensitivity analysis for the model
# "lipophilic_tk". The sensitivities are calculated based on perturbations
# about a set of parameter values selected for rats exposed to hexachloro-
# benzene (HCB) in the study of Nakashima et al. (1997).
#
# Author: Dustin Kapraun, US EPA, November 2020
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

# Load essential functions.
source("sim_functions.R")

# Load model.
load_model("lipophilic_tk")


# Define a function to run model simulations based on a parameter vector q.
run_sim <- function(q) {
    # Run a simulation that corresponds to the conditions of the Nakashima et
    # al. (1997) study.
    
    # Simulation times of interest.
    t_obs = q[["t_gest"]] + q[["t_lact"]]
    q[["t_m_end"]] = t_obs
    q[["t_i_end"]] = t_obs
    times = seq(from=0, to=t_obs, by=0.1)
    
    # Ensure that the times corresponding to conception, birth, weaning, and
    # start and stop of dosing are included.
    times = unique(c(times, 0, q[["t_gest"]], q[["t_gest"]] + q[["t_lact"]],
                     q[["t_m_start"]], q[["t_m_end"]], q[["t_i_start"]],
                     q[["t_i_end"]]))
    times = times[order(times)]
    
    # Recalculate any parameters that depend on other parameters!
    q = init_rat_p(q)
    
    # Run simulation.
    out = rat_sim(times, q)
    
    # Return simulation output.
    return(out)
}


comp_sens <- function(q, rel_step=1.0e-2) {
    # Ensure rel_step is positive.
    rel_step = abs(rel_step)

    # Run a simulation for the parameter values in q.
    out_q = run_sim(q)

    # Compute values of the five dose metrics for values in q.
    times = out_q[ , "time"]
    DM1_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 1)
    DM2_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 2)
    DM3_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 3)
    DM4_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 4)
    DM5_q = comp_dose_metric(times, out_q[ , "C_i"], out_q[ , "AUC_i"],
                             q[["t_gest"]], q[["t_lact"]], 5)
    

    # Create a dataframe to store sensitivity indices.
    len_q = length(q)
    sens_df = data.frame(param_val=q,
                         DM1=double(len_q),
                         DM2=double(len_q),
                         DM3=double(len_q),
                         DM4=double(len_q),
                         DM5=double(len_q))

    # For each parameter in q, compute local sensitivity indices for all five
    # dose metrics.
    for (qname in names(q)) {
        # Perturb this parameter by the "rel_step" amount.
        qx = q
        if (is.nan(q[qname])) {
            next
        } else if (abs(q[qname]) >= rel_step / (1 + rel_step)) {
            qx[qname] = q[qname] * (1 + rel_step)
        } else if (q[qname] >= 0) {
            qx[qname] = rel_step
        } else {
            qx[qname] = -rel_step
        }

        # Run a simulation
        out_qx = run_sim(qx)

        # Compute values of the five dose metrics for values in q.
        times = out_qx[ , "time"]
        DM1_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 1)
        DM2_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 2)
        DM3_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 3)
        DM4_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 4)
        DM5_qx = comp_dose_metric(times, out_qx[ , "C_i"], out_qx[ , "AUC_i"],
                                  qx[["t_gest"]], qx[["t_lact"]], 5)
        
        # Compute sensitivity indices for each dose metric.
        sens_df[qname, "DM1"] = (DM1_qx - DM1_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM1_q)
        sens_df[qname, "DM2"] = (DM2_qx - DM2_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM2_q)
        sens_df[qname, "DM3"] = (DM3_qx - DM3_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM3_q)
        sens_df[qname, "DM4"] = (DM4_qx - DM4_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM4_q)
        sens_df[qname, "DM5"] = (DM5_qx - DM5_q) * q[qname] /
            ((qx[qname] - q[qname]) * DM5_q)
    }

    # Return the dataframe containing the sensitivity analysis results.
    return(sens_df)
}


# Initialize parameters with values used for Nakashima et al. (1997) study.
# Calculate dose (mg/kg) from nominal dose 35.1 nmol per 100 g of diet.
MW = 284.8    # Molecular weight (g/mol or ng/nmol).
d_m_calc = 35.1 * MW / (10 ** 5)

# Effective number of fetuses should yield sufficient weight loss to take the
# dam from her late-term mass to her post-natal (PND 16) body mass.
n_f_calc = (0.3905 - 0.247) / 0.0066

# Effective number of infants should be the average number of suckling pups for
# the dams in the study
n_i_calc = mean(c(15, 14, 14))

# Define simulation parameters.
p <- c(t_lact = 16,        # Duration (d) of lactation/nursing. Set to PND 16.
       M_m_1 = 0.247,      # Maternal mass 1 (kg).
       M_m_2 = 0.3905,     # Maternal mass 2 (kg).
       t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
       t_m_2 = 21,         # Time (d) since conception for maternal mass 2.
       M_i_3 = 0.0286,     # Infant mass 3 (kg).
       t_i_3 = 16,         # Time (d) since birth for infant mass 3.
       n_f = n_f_calc,     # Effective number of fetuses.
       n_i = n_i_calc,     # Number of infants.
       # half_life = 104,    # Half-life (d) from T. Zurlinden model.
       # half_life = 76.1,   # Half-life (d) from T. Zurlinden model.
       # half_life = 94.2,   # Half-life (d) from T. Zurlinden model.
       half_life = 92.4,   # Half-life (d)  based on 10/6/2021 analysis.
       r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
       F_m = 0.094,        # Fraction of maternal mass that is fat.
       F_abs = 0.56,       # Fraction of nominal dose that is absorbed.
       food_dose = 1,      # A boolean flag. Dose is delivered in food if
                           #   nonzero.
       d_m = d_m_calc,     # Dose rate (mg/kg/d or mg/kg) to mother.
       t_m_start = 0,      # Time (d) since conception maternal dose starts.
       t_m_end = 38)       # Time (d) since conception maternal dose ends.

p = init_rat_p(p)

# Run a simulation for the parameter values in p.
out = run_sim(p)

# Plot maternal animal concentrations vs. time from model along with data.
C_m_nmol_per_kg = out[, "C_m"] * (1e6) / MW   # Model estimates (nmol/kg).
C_m_blood = c((12.01+15.48)/2, 3.84)          # Blood data (nmol/L).
C_m_subcfat = c((546.2+909.5)/2, 49.10)       # Subcutaneous fat data (pmol/g).
C_m_perifat = c((445.6 + 358.2)/2, 145.9)     # Perirenal fat data (pmol/g).
C_m_whole = c(145.7, 27.0)
t_data = c(21, 38)                            # Days since conception.
plot(out[, "time"], C_m_nmol_per_kg, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Maternal Animal Concentration (pmol/g)",
     ylim=c(0, 750))
points(t_data, C_m_blood, pch=19, col=vcol[2], cex=1.0)
points(t_data, C_m_subcfat, pch=17, col=vcol[3], cex=1.0)
points(t_data, C_m_perifat, pch=15, col=vcol[4], cex=1.0)
legend("topleft", c("Model, whole body", "Data, blood", "Data, subcutaneous fat",
                    "Data, perirenal fat"),
       col=vcol[1:4], lty=c(1, NA, NA, NA),
       lwd=c(2, NA, NA, NA), pch=c(NA, 19, 17, 15))

# Plot filial animal concentrations vs. time from model along with data.
C_i_nmol_per_kg = out[, "C_i"] * (1e6) / MW  # Model estimates (nmol/kg).
C_i_blood = c(NA, 27.9)          # Blood data (nmol/L).
C_i_subcfat = c(NA, 1495)        # Subcutaneous fat data (pmol/g).
C_i_perifat = c(NA, 2351)        # Perirenal fat data (pmol/g).
# C_i_whole = c(22.72, (27.90 + 1495 + 2351)/3) # Whole body concentration (pmol/g).
C_i_whole = c(22.72, 276.6)
t_data = c(21, 38)                            # Days since conception.
plot(out[, "time"], C_i_nmol_per_kg, type='l', lwd=2, col=vcol[1],
     xlab="Time Since Conception (d)",
     ylab="Filial Animal Concentration (pmol/g)",
     ylim=c(0, 2500))
points(t_data, C_i_blood, pch=19, col=vcol[2], cex=1.0)
points(t_data, C_i_subcfat, pch=17, col=vcol[3], cex=1.0)
points(t_data, C_i_perifat, pch=15, col=vcol[4], cex=1.0)
points(t_data[1], C_i_whole[1], pch=18, col=vcol[5], cex=1.0)
# points(t_data[2], C_i_whole[2], pch=18, col="black", cex=1.0)
legend("topleft", c("Model, whole body", "Data, blood",
                    "Data, subcutaneous fat", "Data, perirenal fat",
                    "Data, whole body"),
       col=vcol[1:5], lty=c(1, NA, NA, NA, NA),
       lwd=c(2, NA, NA, NA, NA), pch=c(NA, 19, 17, 15, 18))

# Perform sensitivity analysis.
sens_df = comp_sens(p)

# Write sensitivity indices to a CSV file.
file_name = "./Output/sens_nakashima1997.csv"
write.csv(sens_df, file_name)

# Remove rows corresponding to unused parameters.
sens_df = sens_df[!is.nan(sens_df[["param_val"]]), ]

# Find all parameters (rows in the data frame) for which at least one of the
# normalized sensitivity indices is greater than 0.2.
sens_df_red = sens_df[rowSums(abs(sens_df[ , 2:ncol(sens_df)]) > 0.25) > 0,
                      2:ncol(sens_df)]

# Remove the parameters t_m_end and t_i_end from consideration. They have been
# set to coincide with the end of lactation, so sensitivity can be observed for
# just t_lact.
# sens_df_red = sens_df_red[row.names(sens_df_red) != "t_m_end", ]
# sens_df_red = sens_df_red[row.names(sens_df_red) != "t_i_end", ]

# Sort the rows based on values of DM1.
sens_df_red = sens_df_red[order(sens_df_red["DM1"]), ]

# Plot normalized sensitivity indices for DM1.
S1_vec = as.vector(sens_df[["DM1"]])
names(S1_vec) = row.names(sens_df)
S1_vec = S1_vec[order(-abs(S1_vec))]
plot(S1_vec)

S1_vec = as.vector(sens_df_red[["DM1"]])
names(S1_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM1_nakashima1997.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S1_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM1")
dev.off()

# Plot normalized sensitivity indices for difference between average blood
# concentration and baseline blood concentration.
S2_vec = as.vector(sens_df[["DM2"]])
names(S2_vec) = row.names(sens_df)
S2_vec = S2_vec[order(-abs(S2_vec))]
plot(S2_vec)

S2_vec = as.vector(sens_df_red[["DM2"]])
names(S2_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM2_nakashima1997.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S2_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-1.0, 1.0),
        xlab="Sensitivity Index for DM2")
dev.off()

# Plot normalized sensitivity indices for peak blood concentration.
S3_vec = as.vector(sens_df[["DM3"]])
names(S3_vec) = row.names(sens_df)
S3_vec = S3_vec[order(-abs(S3_vec))]
plot(S3_vec)

S3_vec = as.vector(sens_df_red[["DM3"]])
names(S3_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM3_nakashima1997.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S3_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM3")
dev.off()

# Plot normalized sensitivity indices for difference between peak blood
# concentration and baseline blood concentration.
S4_vec = as.vector(sens_df[["DM4"]])
names(S4_vec) = row.names(sens_df)
S4_vec = S4_vec[order(-abs(S4_vec))]
plot(S4_vec)

S4_vec = as.vector(sens_df_red[["DM4"]])
names(S4_vec) = row.names(sens_df_red)
file_name = "./Output/sens_DM4_nakashima1997.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(height=S4_vec, horiz=TRUE, col=vcol[1], border=NA,
        cex.names=0.9, las=2, xlim=c(-3.5, 2.5),
        xlab="Sensitivity Index for DM4")
dev.off()

# Plot normalized sensitivity indices for DM1 through DM4, all side-by-side.
file_name = "./Output/sens_all_nakashima1997.tif"
tiff(file_name, units="in", width=5, height=6, res=300)
par(mar=c(5, 6, 4, 1) + 0.1)
barplot(t(as.matrix(sens_df_red[c(4, 3, 2, 1)])), horiz=TRUE,
        col=vcol[c(4, 3, 2, 1)],
        border=NA, beside=TRUE, las=2, xlim=c(-1.0, 1.0),
        xlab="Normalized Local Sensitivity Index")
legend("bottomright", legend=c("Dose Metric 1", "Dose Metric 2",
                               "Dose Metric 3", "Dose Metric 4"),
       fill=vcol[c(1, 2, 3, 4)], border=NA, box.lty=1, cex=0.9)
dev.off()