#------------------------------------------------------------------------------
# sim_functions.R
#
# This file contains R functions for running simulations of toxicokinetics of a
# lipophilic substance in various species.
#
# Author: Dustin Kapraun, U.S. EPA, December 2018.
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Load relevant functions.
source("RMCSim.R")

# Load the lipophilic TK model.
load_model("lipophilic_tk")

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")


#
# Functions to initialize parameter values.
#

init_rat_p <- function(new_p = NULL) {
  # Return a vector containing default parameter values for rat simulations. An
  # optional input parameter vector can be used to assign values other than the
  # default values to some or all of the parameters.
  p <- c(t_gest = 22,        # Duration (d) of pregnancy/gestation.
         t_lact = 21,        # Duration (d) of lactation/nursing.
         M_m_1 = 0.25,       # Maternal mass 1 (kg).
         M_m_2 = 0.273,      # Maternal mass 2 (kg).
         t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
         t_m_2 = 44,         # Time (d) since conception for maternal mass 2.
         n_f = 10,           # Effective number of fetuses.
         n_i = 10,           # Number of infants.
         M_i_1 = 0.0066,     # Infant mass 1 (kg).
         M_i_2 = 0.014,      # Infant mass 2 (kg).
         M_i_3 = 0.028,      # Infant mass 3 (kg).
         M_i_4 = 0.25,       # Infant mass 4 (kg).
         M_i_5 = NaN,        # Infant mass 5 (kg). Not used for rat.
         M_i_6 = NaN,        # Infant mass 6 (kg). Not used for rat.
         t_i_1 = 3,          # Time (d) since birth for infant mass 1.
         t_i_2 = 10,         # Time (d) since birth for infant mass 2.
         t_i_3 = 17,         # Time (d) since birth for infant mass 3.
         t_i_4 = 75,         # Time (d) since birth for infant mass 4.
         t_i_5 = NaN,        # Time (d) since birth for infant mass 5.
         t_i_6 = NaN,        # Time (d) since birth for infant mass 6.
         p_milk = NaN,       # Per body mass rate of milk ingestion (kg/kg/d).
         r_milk_0 = 0.001,   # Rate (kg/d) of milk ingestion at birth.
         r_milk_1 = 0.003,   # Rate (kg/d) of milk ingestion during week 1.
         r_milk_2 = 0.0054,  # Rate (kg/d) of milk ingestion during week 2.
         r_milk_3 = 0.0059,  # Rate (kg/d) of milk ingestion during week 3.
         r_milk_4 = NaN,     # Rate (kg/d) of milk ingestion during week 4.
         half_life = 70.0,   # Half-life (d) of substance in this species.
         F_m = 0.094,        # Fraction of maternal mass that is fat.
         F_milk = 0.154,     # Fraction of breast milk that is fat.
         r_f_m = 0.35,       # Ratio of fetal and maternal concentrations. Ando
                             #   et al. (1978) measured fat fraction of 3.3
                             #   percent in newborn pups. 0.033/0.094 = 0.35
         F_abs = 0.9,        # Fraction of nominal dose that is absorbed.
         food_dose = 0,      # A boolean flag. Dose is delivered in food if
                             #   nonzero.
         d_m = 0,            # Dose rate (mg/kg/d or mg/kg) to mother.
         t_m_start = 0,      # Time (d) since conception maternal dose starts.
         t_m_end = 1,        # Time (d) since conception maternal dose ends.
         A_m_init = 0,       # Initial amount (mg) in mother.
         A_i_init = 0,       # Initial amount (mg) in infant.
         d_i = 0,            # Dose rate (mg/kg/d or mg/kg) to infant.
         t_i_start = 0,      # Time (d) since conception infant dose starts.
         t_i_end = 1)        # Time (d) since conception infant dose ends.
  
  # If "new_p" is not NULL, replace default parameter values with values from
  # that vector.
  if (!is.null(new_p)) {
    if (!all(names(new_p) %in% c(names(p)))) {
      stop("Illegal parameter name in 'new_p'.")
    } else {
      p[names(new_p)] <- new_p
    }
  }
  
  return(p)
}


init_mouse_p <- function(new_p = NULL) {
  # Return a vector containing default parameter values for mouse simulations.
  # An optional input parameter vector can be used to assign values other than
  # the default values to some or all of the parameters.
  p <- c(t_gest = 18,        # Duration (d) of pregnancy/gestation.
         t_lact = 21,        # Duration (d) of lactation/nursing.
         M_m_1 = 0.0255,     # Maternal mass 1 (kg).
         M_m_2 = 0.0318,     # Maternal mass 2 (kg).
         t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
         t_m_2 = 25,         # Time (d) since conception for maternal mass 2.
         n_f = 6,            # Effective number of fetuses.
         n_i = 6,            # Number of infants.
         M_i_1 = 0.0014,     # Infant mass 1 (kg).
         M_i_2 = 0.00608,    # Infant mass 2 (kg).
         M_i_3 = 0.00885,    # Infant mass 3 (kg).
         M_i_4 = 0.03,       # Infant mass 4 (kg).
         M_i_5 = NaN,        # Infant mass 5 (kg). Not used for mouse.
         M_i_6 = NaN,        # Infant mass 6 (kg). Not used for mouse.
         t_i_1 = 1,          # Time (d) since birth for infant mass 1.
         t_i_2 = 10,         # Time (d) since birth for infant mass 2.
         t_i_3 = 18,         # Time (d) since birth for infant mass 3.
         t_i_4 = 45,         # Time (d) since birth for infant mass 4.
         t_i_5 = NaN,        # Time (d) since birth for infant mass 5.
         t_i_6 = NaN,        # Time (d) since birth for infant mass 6.
         p_milk = NaN,       # Per body mass rate of milk ingestion (kg/kg/d).
         r_milk_0 = 0.0001,  # Rate (kg/d) of milk ingestion at birth.
         r_milk_1 = 0.0003,  # Rate (kg/d) of milk ingestion during week 1.
         r_milk_2 = 0.00054, # Rate (kg/d) of milk ingestion during week 2.
         r_milk_3 = 0.00059, # Rate (kg/d) of milk ingestion during week 3.
         r_milk_4 = NaN,     # Rate (kg/d) of milk ingestion during week 4.
         half_life = 68.6,   # Half-life (d) of substance in this species.
         F_m = 0.229,        # Fraction of maternal mass that is fat.
         F_milk = 0.264,     # Fraction of breast milk that is fat.
         r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
         F_abs = 0.9,        # Fraction of nominal dose that is absorbed.
         food_dose = 0,      # A boolean flag. Dose is delivered in food if
                             #   nonzero.
         d_m = 0,            # Dose rate (mg/kg/d or mg/kg) to mother.
         t_m_start = 0,      # Time (d) since conception maternal dose starts.
         t_m_end = 1,        # Time (d) since conception maternal dose ends.
         A_m_init = 0,       # Initial amount (mg) in mother.
         A_i_init = 0,       # Initial amoung (mg) in infant.
         d_i = 0,            # Dose rate (mg/kg/d or mg/kg) to infant.
         t_i_start = 0,      # Time (d) since conception infant dose starts.
         t_i_end = 1)        # Time (d) since conception infant dose ends.
  
  # If "new_p" is not NULL, replace default parameter values with values from
  # that vector.
  if (!is.null(new_p)) {
    if (!all(names(new_p) %in% c(names(p)))) {
      stop("Illegal parameter name in 'new_p'.")
    } else {
      p[names(new_p)] <- new_p
    }
  }
  
  return(p)
}


init_mink_p <- function(new_p = NULL) {
  # Return a vector containing default parameter values for mink simulations.
  # An optional input parameter vector can be used to assign values other than
  # the default values to some or all of the parameters.
  p <- c(t_gest = 52,        # Duration (d) of pregnancy/gestation.
         t_lact = 56,        # Duration (d) of lactation/nursing.
         M_m_1 = 1.0,        # Maternal mass 1 (kg).
         M_m_2 = 1.0,        # Maternal mass 2 (kg).
         t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
         t_m_2 = 2,          # Time (d) since conception for maternal mass 2.
         n_f = 5,            # Effective number of fetuses.
         n_i = 5,            # Number of infants.
         M_i_1 = 0.00946,    # Infant mass 1 (kg).
         M_i_2 = 0.1613,     # Infant mass 2 (kg).
         M_i_3 = 0.9325,     # Infant mass 3 (kg).
         M_i_4 = 1.3618,     # Infant mass 4 (kg).
         M_i_5 = NaN,        # Infant mass 5 (kg). Not used for mink.
         M_i_6 = NaN,        # Infant mass 6 (kg). Not used for mink.
         t_i_1 = 1,          # Time (d) since birth for infant mass 1.
         t_i_2 = 28,         # Time (d) since birth for infant mass 2.
         t_i_3 = 90,         # Time (d) since birth for infant mass 3.
         t_i_4 = 174,        # Time (d) since birth for infant mass 4.
         t_i_5 = NaN,        # Time (d) since birth for infant mass 5.
         t_i_6 = NaN,        # Time (d) since birth for infant mass 6.
         p_milk = NaN,       # Per body mass rate of milk ingestion (kg/kg/d).
         r_milk_0 = 0.007,   # Rate (kg/d) of milk ingestion at birth.
         r_milk_1 = 0.0130,  # Rate (kg/d) of milk ingestion during week 1.
         r_milk_2 = 0.0222,  # Rate (kg/d) of milk ingestion during week 2.
         r_milk_3 = 0.0286,  # Rate (kg/d) of milk ingestion during week 3.
         r_milk_4 = 0.0328,  # Rate (kg/d) of milk ingestion during week 4.
         half_life = 74.2,   # Half-life (d) of substance in this species.
         F_m = 0.312,        # Fraction of maternal mass that is fat.
         F_milk = 0.066,     # Fraction of breast milk that is fat.
         r_f_m = 0.35,       # Ratio of fetal and maternal concentrations.
         F_abs = 0.9,        # Fraction of nominal dose that is absorbed.
         food_dose = 0,      # A boolean flag. Dose is delivered in food if
                             #   nonzero.
         d_m = 0,            # Dose rate (mg/kg/d or mg/kg) to mother.
         t_m_start = 0,      # Time (d) since conception maternal dose starts.
         t_m_end = 1,        # Time (d) since conception maternal dose ends.
         A_m_init = 0,       # Initial amount (mg) in mother.
         A_i_init = 0,       # Initial amoung (mg) in infant.
         d_i = 0,            # Dose rate (mg/kg/d or mg/kg) to infant.
         t_i_start = 0,      # Time (d) since conception infant dose starts.
         t_i_end = 1)        # Time (d) since conception infant dose ends.
  
  # If "new_p" is not NULL, replace default parameter values with values from
  # that vector.
  if (!is.null(new_p)) {
    if (!all(names(new_p) %in% c(names(p)))) {
      stop("Illegal parameter name in 'new_p'.")
    } else {
      p[names(new_p)] <- new_p
    }
  }
  
  return(p)
}


init_monkey_p <- function(new_p = NULL) {
  # Return a vector containing default parameter values for monkey simulations.
  # An optional input parameter vector can be used to assign values other than
  # the default values to some or all of the parameters.
  p = c(t_gest = 168,       # Duration (d) of pregnancy/gestation.
        t_lact = 154,       # Duration (d) of lactation/nursing.
        M_m_1 = 6.6,        # Maternal mass 1 (kg).
        M_m_2 = 6.6,        # Maternal mass 2 (kg).
        t_m_1 = 1,          # Time (d) since conception for maternal mass 1.
        t_m_2 = 2,          # Time (d) since conception for maternal mass 2.
        n_f = 1,            # Effective number of fetuses.
        n_i = 1,            # Number of infants.
        M_i_1 = 0.4775,     # Infant mass 1 (kg).
        M_i_2 = 0.9375,     # Infant mass 2 (kg).
        M_i_3 = 1.4275,     # Infant mass 3 (kg).
        M_i_4 = 2.1925,     # Infant mass 4 (kg).
        M_i_5 = 3.4275,     # Infant mass 5 (kg).
        M_i_6 = 5.270,      # Infant mass 6 (kg).
        t_i_1 = 1,          # Time (d) since birth for infant mass 1.
        t_i_2 = 91,         # Time (d) since birth for infant mass 2.
        t_i_3 = 182,        # Time (d) since birth for infant mass 3.
        t_i_4 = 365,        # Time (d) since birth for infant mass 4.
        t_i_5 = 730,        # Time (d) since birth for infant mass 5.
        t_i_6 = 1095,       # Time (d) since birth for infant mass 6.
        p_milk = 0.1,       # Per body mass rate of milk ingestion (kg/kg/d).
        half_life = 109.5,  # Half-life (d) of substance in this species.
        F_m = 0.199,        # Fraction of maternal mass that is fat.
        F_milk = 0.054,     # Fraction of breast milk that is fat.
        r_f_m = 0.5,        # Ratio of fetal and maternal concentrations. We
                            #   use the default human value as the default
                            #   as the default monkey value.
        F_abs = 0.9,        # Fraction of nominal dose that is absorbed.
        food_dose = 0,      # A boolean flag. Dose is delivered in food if
                            #   nonzero.
        d_m = 0,            # Dose rate (mg/kg/d or mg/kg) to mother.
        t_m_start = 0,      # Time (d) since conception maternal dose starts.
        t_m_end = 1,        # Time (d) since conception maternal dose ends.
        A_m_init = 0,       # Initial amount (mg) in mother.
        A_i_init = 0,       # Initial amoung (mg) in infant.
        d_i = 0,            # Dose rate (mg/kg/d or mg/kg) to infant.
        t_i_start = 0,      # Time (d) since conception infant dose starts.
        t_i_end = 1)        # Time (d) since conception infant dose ends.
  
  # If "new_p" is not NULL, replace default parameter values with values from
  # that vector.
  if (!is.null(new_p)) {
    if (!all(names(new_p) %in% c(names(p)))) {
      stop("Illegal parameter name in 'new_p'.")
    } else {
      p[names(new_p)] <- new_p
    }
  }
  
  return(p)
}


init_human_p <- function(new_p = NULL) {
  # Return a vector containing default parameter values for human simulations.
  # An optional input parameter vector can be used to assign values other than
  # the default values to some or all of the parameters.
  p = c(t_gest = 0.75 * 365,  # Duration (d) of pregnancy/gestation.
        t_lact = 1.0 * 365,   # Duration (d) of lactation/nursing.
        half_life = 48665,    # Half-life (d) of substance in this species.
        F_m = 0.346,          # Fraction of maternal mass that is fat.
        F_milk = 0.039,       # Fraction of breast milk that is fat.
        r_f_m = 0.5,          # Ratio of fetal and maternal concentrations.
                              #   Eguchi et al. (2018) measured the ratio for
                              #   several PCBs and found values between 0.124
                              #   and 0.234. We use the midpoint of this range
                              #   as the default value.
        F_abs = 0.9,          # Fraction of nominal dose that is absorbed.
        food_dose = 0,        # A boolean flag. Dose is delivered in food if
                              #   nonzero.
        d_m = 0,              # Dose rate (mg/kg/d or mg/kg) to mother.
        A_m_init = 0)         # Initial amount (mg) in mother.
  
  # If "new_p" is not NULL, replace default parameter values with values from
  # that vector.
  if (!is.null(new_p)) {
    if (!all(names(new_p) %in% c(names(p)))) {
      stop("Illegal parameter name in 'new_p'.")
    } else {
      p[names(new_p)] <- new_p
    }
  }
  
  return(p)
}

#
# Functions for performing simulations of TK for lipophlic chemicals in various
# animal species, including rat, mouse, mink, monkey, and human. The functions
# are designed to simulate periods of pregnancy and lactation, but can be used
# to simulate TK in non-pregnant animals by ensuring that all simulation times
# (in the "times" input vector) are less than zero, as zero is always assumed
# to coincide with conception.
#

rat_sim <- function(times=NULL, p=NULL) {
  # Perform a rat simulation and return the results (values of state variables
  # and outputs of the lipophilic TK model) for all simulation times.

  # If p is NULL, or if not all parameters are provided in p, use default
  # values for the parameters not provided.
  p = init_rat_p(p)
  
  # If times is NULL, use default times for simulation.
  if (is.null(times)) {
    t_start = min(0, p[["t_m_start"]])
    t_end = max(p[["t_gest"]] + p[["t_lact"]], p[["t_i_end"]])
    times = seq(from=t_start, to=t_end, by=0.1)
  }
  
  # Print an error message if there is a problem with the input parameters
  # relevant to dam mass and infant mass.
  if (p[["t_m_1"]] >= p[["t_m_2"]]) {
    stop("Time t_m_1 must be before time t_m_2.")
  }
  if (p[["M_m_1"]] <= 0) {
    stop("M_m_1 must be positive.")
  }
  if (p[["M_m_2"]] <= 0) {
    stop("M_m_2 must be positive.")
  }
  if (p[["t_i_1"]] >= p[["t_i_2"]]) {
    stop("Time t_i_1 must be before time t_i_2.")
  }
  if (p[["t_i_2"]] >= p[["t_i_3"]]) {
    stop("Time t_i_2 must be before time t_i_3.")
  }
  if (p[["t_i_3"]] >= p[["t_i_4"]]) {
    stop("Time t_i_3 must be before time t_i_4.")
  }
  if (p[["M_i_1"]] <= 0) {
    stop("M_i_1 must be positive.")
  }
  if (p[["M_i_2"]] <= 0) {
    stop("M_i_2 must be positive.")
  }
  if (p[["M_i_3"]] <= 0) {
    stop("M_i_3 must be positive.")
  }
  if (p[["M_i_4"]] <= 0) {
    stop("M_i_4 must be positive.")
  }
  if (is.finite(p[["M_i_5"]])) {
    if (p[["t_i_4"]] >= p[["t_i_5"]]) {
      stop("Time t_i_4 must be before time t_i_5.")
    }
    if (p[["t_i_5"]] >= p[["t_i_6"]]) {
      stop("Time t_i_5 must be before time t_i_6.")
    }
    if (p[["M_i_5"]] <= 0) {
      stop("M_i_5 must be positive.")
    } 
    if (p[["M_i_6"]] <= 0) {
      stop("M_i_6 must be positive.")
    } 
  }
  
  # Print an error message if there is a problem with the input parameters
  # relevant to dose start and stop times.
  if (p[["t_m_start"]] >= p[["t_m_end"]]) {
    stop("Time t_m_start must be before time t_m_end.")
  }
  if (p[["t_i_start"]] >= p[["t_i_end"]]) {
    stop("Time t_i_start must be before time t_i_end.")
  }
  
  # Calculate total mass of pups at birth.
  M_pups = p[["n_f"]] * p[["M_i_1"]]
  
  # If the simulation starts before birth, run the pregnancy simulation.
  if (times[1] <= p[["t_gest"]]) {
    # Generate points to interpolate for calculations of dam mass up to moment of
    # birth.
    if (p[["t_m_2"]] <= p[["t_gest"]]) { # Case 1: t_m_2 <= t_gest.
      # If M_m_2 occurs before birth ...
      if (p[["M_m_2"]] < (p[["M_m_1"]] + M_pups)) {
        # If M_m_2 is not large enough to account for the mass of the pups at
        # birth, calculate a third maternal mass that is large enough.
        M_m_birth = p[["M_m_1"]] + M_pups  # Mass just before birth.
      } else {
        # Otherwise, M_m_2 is large enough and we don't need to calculate a
        # third maternal mass.
        M_m_birth = p[["M_m_2"]]           # Mass just before birth.
      }
      # Maternal mass will change (in a linear fashion) from M_m_1 to M_m_2,
      # and finally to M_m_birth (which may be equal to M_m_2, if that value
      # is large enough to account for mass of pups at birth).
      t_m_vec = c(p[["t_m_1"]], p[["t_m_2"]], p[["t_gest"]])
      M_m_vec = c(p[["M_m_1"]], p[["M_m_2"]], M_m_birth)
    } else if (p[["t_m_1"]] <= p[["t_gest"]]) { # Case 2: t_m_1 <= t_gest < t_m_2.
      # If M_m_2 occurs after birth, calculate a maternal mass that is large
      # enough such that the loss of the mass of the pups at birth will return
      # total maternal mass to M_m_2 after birth.
      M_m_birth = p[["M_m_2"]] + M_pups  # Mass just before birth.
      t_m_vec = c(p[["t_m_1"]], p[["t_gest"]])
      M_m_vec = c(p[["M_m_1"]], M_m_birth)
    } else {
      # We require at least one maternal mass value to represent the time
      # before birth occurs.
      stop("Time t_m_1 must be before time t_gest.")
    }
    
    # Rat dam mass interpolation points up to moment of birth.
    M_mf_in = cbind(times=t_m_vec, mass=M_m_vec)
    
    # Rat infant mass interpolation points up to moment of birth.
    # Infant mass is assumed to be zero throughout gestation and concentration
    # in the fetuses is calculated as a proportion of concentration in the
    # mother.
    M_i_in = cbind(times=c(0, 1), mass=c(0, 0))
    
    # Rat breast milk ingestion rate interpolation points.
    # Infant milk consumption rate is assumed to be zero throughout gestation.
    R_milk_in = cbind(times=c(0, 1), rate=c(0, 0))
    
    # Dosing events. Turn dosing on and off at specified times.
    df_dose = data.frame(var=c("d_m", "d_m", "d_i", "d_i"),
                         time=c(p[["t_m_start"]], p[["t_m_end"]],
                                p[["t_i_start"]], p[["t_i_end"]]),
                         value=c(p[["d_m"]], 0, p[["d_i"]], 0),
                         method=rep("replace", 4))
    df_dose = df_dose[order(df_dose[["time"]]), ]
    rownames(df_dose) = 1:nrow(df_dose)
    
    # Mass of mother just after birth.
    M_m_b = M_m_birth - M_pups
    
    # Ratio of concentrations in mother and mother + fetus(es). At conception,
    # this ratio is 1. At birth this ratio can be calculated as shown below.
    # assume a linear transition in the values of this ratio between conception
    # and birth.
    r_m_mf_0 = 1.0
    r_m_mf_b = (M_m_b + M_pups) / (M_m_b + p[["r_f_m"]] * M_pups)
    r_m_mf_in = cbind(times=c(0, p[["t_gest"]]), ratio=c(r_m_mf_0, r_m_mf_b))
    
    # Get parameters and initial values of state variables.
    parms = initParms()
    parms["half_life"] = p[["half_life"]]
    parms["F_m"] = p[["F_m"]]
    parms["F_milk"] = p[["F_milk"]]
    parms["r_f_m"] = p[["r_f_m"]]
    parms["F_abs"] = p[["F_abs"]]
    parms["n_i"] = p[["n_i"]]
    parms["food_dose"] = p[["food_dose"]]
    parms = initParms(parms)   # Update calculated parameters.
    Y0 = initStates(parms)
    Y0["A_mf"] = p[["A_m_init"]]
    Y0["A_i"] = 0
    Y0["T_in"] = Y0[["A_mf"]]
    
    # Run simulation for times leading up to birth.
    times1 = times[times <= p[["t_gest"]]]
    out1 = run_model("lipophilic_tk", times1, Y0, parms,
                     list(M_mf_in, M_i_in, R_milk_in, r_m_mf_in),
                     list(method="linear", rule=2, ties="ordered"),
                     list(data=df_dose))
  
    # If this simulation does not incorporate any lactation/nursing period,
    # stop here.
    if (max(times) <= p[["t_gest"]]) {
      return(out1)
    }
  }
  
  # Continue with a simulation of the lactation/nursing period if necessary...
  
  # If there are results from a pregnancy simulation (in "out1"), use those to
  # set initial conditions.
  if (times[1] <= p[["t_gest"]]) {
    # Apportion the amount of substance in the mother at the moment of birth to
    # the mother and the infant(s) according to body mass. Use these values to
    # set the initial conditions for the post-birth simulation.
    M_m_birth = out1[[nrow(out1), "M_mf"]] - M_pups
    M_i_birth = p[["M_i_1"]]
    C_m_birth = out1[[nrow(out1), "C_m"]]
    C_i_birth = out1[[nrow(out1), "C_i"]]
    Y0["A_mf"] = C_m_birth * M_m_birth
    Y0["A_i"] = C_i_birth * M_i_birth
    Y0["AUC_m"] = out1[[nrow(out1), "AUC_m"]]
    Y0["AUC_i"] = out1[[nrow(out1), "AUC_i"]]
    Y0["d_m"] = out1[[nrow(out1), "d_m"]]
    Y0["d_i"] = out1[[nrow(out1), "d_i"]]
    Y0["T_in"] = out1[[nrow(out1), "T_in"]]
    Y0["T_out"] = out1[[nrow(out1), "T_out"]] +
      C_i_birth * M_i_birth * (p[["n_f"]] - p[["n_i"]])
  } else {
    # Get parameters and initial values of state variables.
    parms = initParms()
    parms["half_life"] = p[["half_life"]]
    parms["F_m"] = p[["F_m"]]
    parms["F_milk"] = p[["F_milk"]]
    parms["r_f_m"] = p[["r_f_m"]]
    parms["F_abs"] = p[["F_abs"]]
    parms["n_i"] = p[["n_i"]]
    parms["food_dose"] = p[["food_dose"]]
    parms = initParms(parms)   # Update calculated parameters.
    Y0 = initStates(parms)
    Y0["A_mf"] = p[["A_m_init"]]
    Y0["A_i"] = p[["A_i_init"]]
    Y0["T_in"] = Y0[["A_mf"]] + Y0[["A_i"]]
  }
  
  # Set dosing data frame.
  # Dosing events. Turn dosing on and off at specified times.
  df_dose = data.frame(var=c("d_m", "d_m", "d_i", "d_i"),
                       time=c(p[["t_m_start"]], p[["t_m_end"]],
                              p[["t_i_start"]], p[["t_i_end"]]),
                       value=c(p[["d_m"]], 0, p[["d_i"]], 0),
                       method=rep("replace", 4))
  df_dose = df_dose[order(df_dose[["time"]]), ]
  rownames(df_dose) = 1:nrow(df_dose)
  
  # Set r_m_mf_in parameter (which is not used).
  r_m_mf_in = cbind(times=c(0, 1), ratio=c(0, 0))
  
  
  # Generate points to interpolate for calculations of dam mass after moment of
  # birth.
  if (p[["t_m_2"]] <= p[["t_gest"]]) { # Case 1: t_m_2 <= t_gest.
    if (p[["M_m_2"]] < (p[["M_m_1"]] + M_pups)) {
      # If M_m_2 is not large enough to account for the mass of the pups at
      # birth, the maternal mass grew to M_m_1 + M_pups at the end of pregnancy
      # and should now return to M_m_1.
      M_m_birth = p[["M_m_1"]]           # Mass just after birth.
    } else {
      # Otherwise, the mass should return to M_m_2 minus M_pups.
      M_m_birth = p[["M_m_2"]] - M_pups  # Mass just after birth.
    }
    # The maternal mass will remain constant during lactation.
    t_m_vec = c(p[["t_gest"]], p[["t_gest"]] + 1)
    M_m_vec = c(M_m_birth, M_m_birth)
  } else if (p[["t_m_1"]] <= p[["t_gest"]]) { # Case 2: t_m_1 <= t_gest < t_m_2.
    # The maternal mass will remain constant during lactation.
    M_m_birth = p[["M_m_2"]]             # Mass just after birth.
    t_m_vec = c(p[["t_gest"]], p[["t_gest"]] + 1)
    M_m_vec = c(M_m_birth, M_m_birth)
  } else {
    stop("Time t_m_1 must be before time t_gest.")
  }
  
  # Rat dam mass interpolation points after moment of birth.
  M_mf_in = cbind(times=t_m_vec, mass=M_m_vec)
  
  # Rat infant mass interpolation points.
  if (is.nan(p[["M_i_5"]])) {
    t_i_vec = p[["t_gest"]] + c(-1e-6, p[["t_i_1"]], p[["t_i_2"]],
                                p[["t_i_3"]], p[["t_i_4"]])
    M_i_vec = c(p[["M_i_1"]], p[["M_i_1"]], p[["M_i_2"]], p[["M_i_3"]],
                p[["M_i_4"]])
  } else {
    t_i_vec = p[["t_gest"]] + c(-1e-6, p[["t_i_1"]], p[["t_i_2"]],
                                p[["t_i_3"]], p[["t_i_4"]], p[["t_i_5"]],
                                p[["t_i_6"]])
    M_i_vec = c(p[["M_i_1"]], p[["M_i_1"]], p[["M_i_2"]], p[["M_i_3"]],
                p[["M_i_4"]], p[["M_i_5"]], p[["M_i_6"]])
  }
  M_i_in = cbind(times=t_i_vec, mass=M_i_vec)
  
  # Rat breast milk ingestion rate interpolation points.
  if (is.nan(p[["p_milk"]])) {
    t_milk_0 = p[["t_gest"]]
    t_milk_1e = t_milk_0 + 7
    t_milk_2e = t_milk_0 + 14
    t_milk_3e = t_milk_0 + 21
    r_milk_0 = p[["r_milk_0"]]
    r_milk_1e = r_milk_0 + 7.0 * (p[["r_milk_1"]] - p[["r_milk_0"]]) / 3.5
    r_milk_2e = r_milk_1e + 7.0 * (p[["r_milk_2"]] - r_milk_1e) / 3.5
    r_milk_3e = r_milk_2e + 7.0 * (p[["r_milk_3"]] - r_milk_2e) / 3.5
    if (is.nan(p[["r_milk_4"]])) {
      t_milk_4e = t_milk_0 + p[["t_lact"]]
      r_milk_4e = 0.0
      t_milk_vec = c(t_milk_0, t_milk_1e, t_milk_2e, t_milk_3e, t_milk_4e)
      r_milk_vec = c(r_milk_0, r_milk_1e, r_milk_2e, r_milk_3e, r_milk_4e)
    } else {
      t_milk_4e = t_milk_0 + 28
      r_milk_4e = r_milk_3e + 7.0 * (p[["r_milk_4"]] - r_milk_3e) / 3.5
      t_milk_5e = t_milk_0 + p[["t_lact"]]
      r_milk_5e = 0.0
      t_milk_vec = c(t_milk_0, t_milk_1e, t_milk_2e, t_milk_3e, t_milk_4e,
                     t_milk_5e)
      r_milk_vec = c(r_milk_0, r_milk_1e, r_milk_2e, r_milk_3e, r_milk_4e,
                     r_milk_5e)
    }
  } else { # Milk consumption will be based on infant mass.
    t_wean = p[["t_gest"]] + p[["t_lact"]]
    M_wean = approx(t_i_vec, M_i_vec, xout=t_wean)$y
    t_milk_vec = c(t_i_vec, t_wean)
    r_milk_vec = p[["p_milk"]] * c(M_i_vec, M_wean)
    r_milk_vec = r_milk_vec[t_milk_vec <= t_wean]
    t_milk_vec = t_milk_vec[t_milk_vec <= t_wean]
    t_milk_vec = c(t_milk_vec, t_wean)
    r_milk_vec = c(r_milk_vec, 0.0)
  }
  R_milk_in = cbind(times=t_milk_vec, rate=r_milk_vec)
  
  # Run simulation for times after birth.
  times2 = times[times >= p["t_gest"]]
  out2 = run_model("lipophilic_tk", times2, Y0, parms,
                   list(M_mf_in, M_i_in, R_milk_in, r_m_mf_in),
                   list(method="linear", rule=2, ties="ordered"),
                   list(data=df_dose))
  
  # Assemble output data frame. Combine pre-birth and post-birth simulations if
  # necessary.
  if (times[1] <= p[["t_gest"]]) {
    out = rbind(out1[1:nrow(out1)-1, ], out2)
    # out = rbind(out1, out2[2, nrow(out2)])
  } else {
    out = out2
  }
  
  # Return output data frame.
  return(out)
}


mouse_sim <- function(times=NULL, p=NULL) {
  # Perform a mouse simulation and return the results (values of state
  # variables and outputs of the lipophilic TK model) for all simulation times.
  
  # If p is NULL, or if not all parameters are provided in p, use default
  # values for the parameters not provided.
  p = init_mouse_p(p)
  
  # Run the simulation as for rat and return the result.
  out = rat_sim(times=times, p=p)
}


mink_sim <- function(times=NULL, p=NULL) {
  # Perform a mink simulation and return the results (values of state variables
  # and outputs of the lipophilic TK model) for all simulation times.
  
  # If p is NULL, or if not all parameters are provided in p, use default
  # values for the parameters not provided.
  p = init_mink_p(p)
  
  # Run the simulation as for rat and return the result.
  out = rat_sim(times=times, p=p)
}


monkey_sim <- function(times=NULL, p=NULL) {
  # Perform a monkey simulation and return the results (values of state
  # variables and outputs of the lipophilic TK model) for all simulation times.
  
  # If p is NULL, or if not all parameters are provided in p, use default
  # values for the parameters not provided.
  p = init_monkey_p(p)
  
  # Run the simulation as for rat and return the result.
  out = rat_sim(times=times, p=p)
}


human_sim <- function(times=NULL, p=NULL, M_m_df1=NULL, M_m_df2=NULL,
                      M_m_df3=NULL, M_i_df1=NULL, M_i_df2=NULL, preg=TRUE) {
  # Perform a human simulation and return the results (values of state
  # variables and outputs of the lipophilic TK model) for all simulation times.
  
  # If p is NULL, or if not all parameters are provided in p, use default
  # default values for the parameters not provided.
  p = init_human_p(p)
  
  # If t is NULL, use default times for simulation. The default for a pregnancy
  # simulation is from birth of the mother (24.25 y before conception) until 
  # weaning (t_gest + t_lact d after conception). The default for a non-
  # pregnant adult simulation is from birth (age 0 y) through age 78 y.
  if (is.null(times)) {
    if (preg) {
      t_start = -24.25 * 365
      t_end = p[["t_gest"]] + p[["t_lact"]]
      times = seq(from=t_start, to=t_end, by=0.25)
    } else {
      t_start = 0
      t_end = 78 * 365    # Simulate 78 years.
      times = seq(from=t_start, to=t_end, by=1)
    }
  }
  
  # If not provided, obtain time course data for mass of human mother.
  if (is.null(M_m_df1)){
    M_m_df1 = read.csv("human_female_mass_0_to_20.csv", header=FALSE,
                       col.names=c("Age (y)", "Mass (kg)"),
                       check.names=FALSE)
  }
  if (is.null(M_m_df2)) {
    if (preg) {
      M_m_df2 = read.csv("human_female_mass_20_to_25_pregnancy.csv",
                         header=FALSE,
                         col.names=c("Age (y)", "Mass (kg)"),
                         check.names=FALSE)
    } else {
      M_m_df2 = read.csv("human_female_mass_20_to_75.csv",
                         header=FALSE,
                         col.names=c("Age (y)", "Mass (kg)"),
                         check.names=FALSE)
    }
  }
  if (is.null(M_m_df3) && preg) {
    M_m_df3 = read.csv("human_female_mass_25_to_26_postnatal.csv",
                       header=FALSE, col.names=c("Age (y)", "Mass (kg)"),
                       check.names=FALSE)
  }
  
  # If not provided, obtain time course data for mass of human infant
  # (through adulthood).
  if (preg) {
    if (is.null(M_i_df1)) {
      M_i_df1 = read.csv("human_female_mass_0_to_20.csv", header=FALSE,
                         col.names=c("Age (y)", "Mass (kg)"),
                         check.names=FALSE)
    }
    if (is.null(M_i_df2)) {
      M_i_df2 = read.csv("human_female_mass_20_to_75.csv", header=FALSE,
                         col.names=c("Age (y)", "Mass (kg)"),
                         check.names=FALSE)
    }
  }
  
  # Maternal mass interpolation points up to moment of birth. Assume the
  # moment of birth never occurs when preg is FALSE.
  M_m_df = rbind(M_m_df1, M_m_df2)
  if (preg) {
    t_m_vec = (M_m_df[["Age (y)"]] - 24.25) * 365
  } else {
    t_m_vec = M_m_df[["Age (y)"]] * 365
  }
  M_m_vec = M_m_df[["Mass (kg)"]]
  M_mf_in = cbind(times=t_m_vec, mass=M_m_vec)
  
  # Infant mass interpolation points up to moment of birth.
  M_i_in = cbind(times=c(0, 1), mass=c(0, 0))
  
  # Human breast milk ingestion rate interpolation points up to moment of
  # birth.
  R_milk_in = cbind(times=c(0, 1), rate=c(0, 0))
  
  # Set the ratio of the concentration in the mother to the concentration in
  # the mother plus fetuses. If this is not a pregnancy simulation, the ratio
  # will always be one.
  if (preg) {
    # Mass of mother (plus products of conception other than the infant) just
    # after birth.
    M_m_birth = M_m_df2[[nrow(M_m_df2), "Mass (kg)"]]
    M_i_birth = M_i_df1[[1, "Mass (kg)"]]
    M_m_b = M_m_birth - M_i_birth
  
    # Ratio of concentrations in mother and mother + fetus(es). At conception,
    # this ratio is 1. At birth this ratio can be calculated as shown below.
    # assume a linear transition in the values of this ratio between conception
    # and birth. 
    r_m_mf_0 = 1.0
    r_m_mf_b = (M_m_b + M_i_birth) / (M_m_b + p[["r_f_m"]] * M_i_birth)
    r_m_mf_in = cbind(times=c(0, p[["t_gest"]]), ratio=c(r_m_mf_0, r_m_mf_b))
  } else {
    r_m_mf_in = cbind(times=c(0, 1), ratio=c(1, 1))
  }
  
  # Get parameters and initial values of state variables.
  parms = initParms()
  parms["half_life"] = p[["half_life"]]
  parms["F_m"] = p[["F_m"]]
  parms["F_milk"] = p[["F_milk"]]
  if (preg) {
    parms["r_f_m"] = p[["r_f_m"]]
  } else {
    parms["r_f_m"] = 0
  }
  parms["F_abs"] = p[["F_abs"]]
  parms["n_i"] = 1
  parms["food_dose"] = p[["food_dose"]]
  parms = initParms(parms)   # Update calculated parameters.
  Y0 = initStates(parms)
  Y0["A_mf"] = p[["A_m_init"]]
  Y0["T_in"] = Y0[["A_mf"]]
  Y0["d_m"] = p[["d_m"]]
  
  # Run simulation for times leading up to birth (if preg is TRUE) or all
  # times (if preg is FALSE).
  if (preg) {
    times1 = times[times <= p[["t_gest"]]]
  } else {
    times1 = times
  }
  out1 = run_model("lipophilic_tk", times1, Y0, parms,
                   list(M_mf_in, M_i_in, R_milk_in, r_m_mf_in),
                   list(method="linear", rule=2, ties="ordered"))
  
  # If this simulation does not incorporate any lactation/nursing period, stop
  # here.
  if (preg) {
    if (max(times) <= p[["t_gest"]]) {
      return(out1)
    }
  } else {
    return(out1)
  }
  
  # Otherwise, continue with a simulation of the lactation/nursing period...
  
  # Maternal mass interpolation points after moment of birth.
  M_m_df = M_m_df3
  t_m_vec = (M_m_df[["Age (y)"]] - 24.25) * 365
  M_m_vec = M_m_df[["Mass (kg)"]]
  M_m_in = cbind(times=t_m_vec, mass=M_m_vec)
  
  # Infant mass interpolation points after moment of birth.
  # Shift ages so that they relect elapsed time since conception.
  M_i_df = rbind(M_i_df1, M_i_df2)
  t_i_vec = M_i_df[["Age (y)"]] * 365 + p[["t_gest"]]
  m_i_vec = M_i_df[["Mass (kg)"]]
  M_i_in = cbind(time=t_i_vec, mass=m_i_vec)
  
  # Human breast milk ingestion rate interpolation points.
  t_milk_0 = p[["t_gest"]]
  t_milk_1e = t_milk_0 + 30
  t_milk_2e = t_milk_0 + 90
  t_milk_3e = t_milk_0 + 180
  t_milk_4e = t_milk_0 + 365
  t_milk_5e = t_milk_4e + 1e-6
  r_milk_0 = 0.477
  r_milk_1e = r_milk_0 +  2 * (0.510 - r_milk_0)
  r_milk_2e = r_milk_1e + 2 * (0.690 - r_milk_1e)
  r_milk_3e = r_milk_2e + 2 * (0.770 - r_milk_2e)
  r_milk_4e = r_milk_3e + 2 * (0.620 - r_milk_3e)
  r_milk_5e = 0.0
  t_milk_vec = c(t_milk_0, t_milk_1e, t_milk_2e, t_milk_3e, t_milk_4e,
                 t_milk_5e)
  r_milk_vec = c(r_milk_0, r_milk_1e, r_milk_2e, r_milk_3e, r_milk_4e,
                 r_milk_5e)
  R_milk_in = cbind(times=t_milk_vec, rate=r_milk_vec)
  
  # Apportion the amount of substance in the mother at the moment of birth to
  # the mother and the infant(s) according to body mass. Use these values to
  # set the initial conditions for the post-birth simulation.
  M_m_birth = M_m_df3[[1, "Mass (kg)"]]
  M_i_birth = m_i_vec[1]
  C_m_birth = out1[[nrow(out1), "C_m"]]
  C_i_birth = out1[[nrow(out1), "C_i"]]
  Y0["A_mf"] = C_m_birth * M_m_birth
  Y0["A_i"] = C_i_birth * M_i_birth
  Y0["AUC_m"] = out1[[nrow(out1), "AUC_m"]]
  Y0["AUC_i"] = out1[[nrow(out1), "AUC_i"]]
  Y0["d_m"] = out1[[nrow(out1), "d_m"]]
  Y0["d_i"] = out1[[nrow(out1), "d_i"]]
  Y0["T_in"] = out1[[nrow(out1), "T_in"]]
  Y0["T_out"] = out1[[nrow(out1), "T_out"]] +
    out1[[nrow(out1), "A_mf"]] - Y0[["A_mf"]] - Y0[["A_i"]]
  
  # Create an "event" so that direct dosing of the infant (filial) human
  # begins at weaning and continues through the rest of the simulation.
  df_dose = data.frame(var=c("d_i"),
                       time=c(p[["t_gest"]] + p[["t_lact"]]),
                       value=c(p[["d_m"]]),
                       method=c("replace"))
  
  # Set r_m_mf_in parameter (which is not used).
  r_m_mf_in = cbind(times=c(0, 1), ratio=c(0, 0))
  
  # Run simulation for times after birth.
  times2 = times[times >= p["t_gest"]]
  out2 = run_model("lipophilic_tk", times2, Y0, parms,
                   list(M_m_in, M_i_in, R_milk_in, r_m_mf_in),
                   list(method="linear", rule=2, ties="ordered"),
                   list(data=df_dose))
  
  # Assemble output data frame.
  out = rbind(out1[1:nrow(out1)-1, ], out2)
  
  # Return output data frame.
  return(out)
}




#
# Demonstrations of rat simulations.
#

rat_demo1 <- function() {
  # Simulate rat pregnancy and lactation with an initial bolus dose of 100 mg.

  # Define simulation parameters.
  p = c(A_m_init = 100)     # Initial amount (mg) in mother.
  
  # Run simulation.
  out <- rat_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


rat_demo2 <- function() {
  # Simulate rat pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the mother between 6 d and 28 d after conception.

  # Define simulation parameters.
  p = c(d_m = 6,            # Dose rate (mg/kg/d) to mother.
        t_m_start = 6,      # Time (d) since conception maternal dose starts.
        t_m_end = 28)       # Time (d) since conception maternal dose ends.

  # Run simulation
  out <- rat_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


rat_demo3 <- function() {
  # Simulate an adult (non-pregnant) rat to which a dose of 6 mg/kg/d is
  # applied for 22 days and an observation occurs 28 days after the start of
  # the simulation.
  
  # Adult (non-developmental study) parameters.
  r_dose = 6                # Dose rate (mg/kg/d) to adult animal.
  t_dose = 22               # Duration (d) of dose.
  t_exp = 28                # Duration (d) of experiment
  F_abs = 1.0               # Fraction of dose absorbed.
  r_f_m = 1.0               # Ratio of concentrations in fetus and mother.
                            # Setting this value to 1.0 will cause r_m_mf to be
                            # calculated as 1.0 in the function "rat_sim".
  
  # Define simulation parameters.
  p = c(d_m = r_dose,               # Dose rate (mg/kg/d) to "mother".
        t_m_start = -t_exp,         # Time (d) since conception "maternal" dose
                                    #  starts.
        t_m_end = -t_exp + t_dose,  # Time (d) since conception "maternal" dose
                                    #  ends.
        F_abs = F_abs,
        r_f_m = r_f_m)

  # Define simulation times.
  times = seq(from=-t_exp, to=0, by=0.1)
  
  # Run simulation.
  out <- rat_sim(times=times, p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1] + t_exp, out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot concentration vs. time.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1] + t_exp, out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Beginning of Exposure (d)",
       ylab="Concentration (mg/kg)")
}


rat_demo4 <- function() {
  # Simulate rat pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the pups between 25 d and 30 d after conception (i.e., between
  # 4 d and 9 d after birth).
  
  # Define simulation parameters.
  p = c(d_i = 6,            # Dose rate (mg/kg/d) to infant.
        t_i_start = 25,     # Time (d) since conception infant dose starts.
        t_i_end = 30)       # Time (d) since conception infant dose ends.
  
  # Run simulation.
  out <- rat_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


rat_demo5 <- function() {
  # Simulate rat pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the mother starting 10 d before conception and end 28 d after
  # conception (i.e., 7 d after parturition).
  
  # Define simulation parameters.
  p = c(d_m = 6,            # Dose rate (mg/kg/d) to mother.
        t_m_start = -10,    # Time (d) since conception maternal dose starts.
        t_m_end = 28)       # Time (d) since conception maternal dose ends.
  
  # Run simulation
  out <- rat_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


mouse_demo1 <- function() {
  # Simulate mouse pregnancy and lactation with an initial bolus dose of 100 mg.
  
  # Define simulation parameters.
  p = c(A_m_init = 100)     # Initial amount (mg) in mother.
  
  # Run simulation.
  out <- mouse_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


mouse_demo2 <- function() {
  # Simulate mouse pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the mother between 6 d and 28 d after conception.
  
  # Define simulation parameters.
  p = c(d_m = 6,            # Dose rate (mg/kg/d) to mother.
        t_m_start = 6,      # Time (d) since conception maternal dose starts.
        t_m_end = 28)       # Time (d) since conception maternal dose ends.
  
  # Run simulation.
  out <- mouse_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


mink_demo1 <- function() {
  # Simulate mink pregnancy and lactation with an initial bolus dose of 100 mg.
  
  # Define simulation parameters.
  p = c(A_m_init = 100)     # Initial amount (mg) in mother.
  
  # Run simulation.
  out <- mink_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}

mink_demo2 <- function() {
  # Simulate mink pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the mother between 6 d and 70 d after conception.
  
  # Define simulation parameters.
  p = c(d_m = 6,            # Dose rate (mg/kg/d) to mother.
        t_m_start = 6,      # Time (d) since conception maternal dose starts.
        t_m_end = 70)       # Time (d) since conception maternal dose ends.
  
  # Run simulation.
  out <- mink_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


monkey_demo1 <- function() {
  # Simulate monkey pregnancy and lactation with an initial bolus dose of 100 mg.
  
  # Define simulation parameters.
  p = c(A_m_init = 100)     # Initial amount (mg) in mother.
  
  # Run simulation.
  out <- monkey_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


monkey_demo2 <- function() {
  # Simulate monkey pregnancy and lactation with a constant dose rate of 6 mg/kg/d
  # applied to the mother between 6 d and 200 d after conception.
  
  # Define simulation parameters.
  p = c(d_m = 6,            # Dose rate (mg/kg/d) to mother.
        t_m_start = 6,      # Time (d) since conception maternal dose starts.
        t_m_end = 200)      # Time (d) since conception maternal dose ends.
  
  # Run simulation.
  out <- monkey_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1], out[, "C_m"], type='l', lty=1, col=vcol[1], lwd=2,
       ylim=c(0, ymax),
       xlab="Time Since Conception (d)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1], out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


human_demo1 <- function() {
  # Simulate human pregnancy and lactation with an initial bolus dose of 100 mg.
  
  # Define simulation parameters.
  p = c(A_m_init = 100)       # Initial amount (mg) in mother.
  
  # Run simulation.
  t_start = -24.25 * 365
  t_end = 78.75 * 365          # Simulate to 78.75 years post-conception.
  times = seq(from=t_start, to=t_end, by=0.25)
  out <- human_sim(times=times, p=p)
  # out <- human_sim(p=p)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
    plot(out[ , 1] / 365 + 24.25, out[ , idx], type='l',
         xlab="Age of Mother (y)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1] / 365 + 24.25, out[, "C_m"], type='l', lty=1, col=vcol[1],
       lwd=2, ylim=c(0, ymax),
       xlab="Age of mother (y)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1] / 365 + 24.25, out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


human_demo2 <- function() {
  # Simulate human pregnancy and lactation up until 30 years post-conception
  # with a constant dose of 0.0063 mg/kg/d to the mother throughout and the
  # same dose applied to to the child after weaning.
  
  # Define simulation parameters.
  p = c(d_m = 0.0063)            # Dose rate (mg/kg/d) to mother.

  # Run simulation.
  t_start = -24.25 * 365
  t_end = 30.0 * 365            # Simulate to 30 years post-conception.
  times = seq(from=t_start, to=t_end, by=0.25)
  out <- human_sim(times=times, p=p)
  # out <- human_sim(p=p)
  
  # Plot all output variables vs. time.
  conception_idx = match(0, out[ , 1])
  for (idx in 2:ncol(out)) {
    plot(out[conception_idx:nrow(out), 1] / 365 + 24.25,
         out[conception_idx:nrow(out), idx],
         type='l', xlab="Age of Mother (y)",
         ylab=colnames(out)[idx])
  }
  
  # Plot maternal and fetal/infant concentration vs. time on the same axes.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1] / 365 + 24.25, out[, "C_m"], type='l', lty=1, col=vcol[1],
       lwd=2, ylim=c(0, ymax),
       xlab="Age of mother (y)",
       ylab="Concentration (mg/kg)")
  lines(out[, 1] / 365 + 24.25, out[, "C_i"], lty=2, col=vcol[2], lwd=2)
  legend("topleft", c("mother", "fetus/infant"), lty=c(1, 2), col=vcol[1:2],
         lwd=c(2, 2))
}


human_demo3 <- function() {
  # Simulate an adult (non-pregnant) human to which an initial bolus dose of
  # 100 mg is applied.

  # Define simulation parameters.
  p = c(A_m_init = 100)       # Initial amount (mg) in mother.

  # Run simulation.
  out <- human_sim(p=p, preg=FALSE)

  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
      plot(out[ , 1] / 365, out[ , idx], type='l',
           xlab="Age of Mother (y)",
           ylab=colnames(out)[idx])
  }
  
  # Plot concentration vs. time.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1] / 365 + 24.25, out[, "C_m"], type='l', lty=1, col=vcol[1],
       lwd=2, ylim=c(0, ymax),
       xlab="Age (y)",
       ylab="Concentration (mg/kg)")
}


human_demo4 <- function() {
  # Simulate an adult (non-pregnant) human to which a continouse dose of 0.0063
  # mg/kg/d is applied.
    
  # Define simulation parameters.
  p = c(d_m = 0.0063)            # Dose rate (mg/kg/d) to mother.

  # Run simulation.
  out <- human_sim(p=p, preg=FALSE)
  
  # Plot all output variables vs. time.
  for (idx in 2:ncol(out)) {
      plot(out[ , 1] / 365, out[ , idx], type='l',
           xlab="Age of Mother (y)",
           ylab=colnames(out)[idx])
  }
  
  # Plot concentration vs. time.
  ymax = max(c(out[, "C_m"], out[, "C_i"]))
  plot(out[, 1] / 365 + 24.25, out[, "C_m"], type='l', lty=1, col=vcol[1],
       lwd=2, ylim=c(0, ymax),
       xlab="Age (y)",
       ylab="Concentration (mg/kg)")
}


comp_dose_metric <- function(times, conc, AUC, t_gest, t_lact, DM_code) {
  conception_idx = match(0, times)
  birth_idx = match(t_gest, times)
  wean_idx = match(t_gest + t_lact, times)

  if (DM_code == 1) {         # Peak concentration during gestation/nursing.
    out = (max(conc[conception_idx:wean_idx]))
  } else if (DM_code == 2) {  # Average concentration during gestation/nursing.
    out = (AUC[wean_idx] - AUC[conception_idx]) / (times[wean_idx]
      - times[conception_idx])
  } else if (DM_code == 3) {  # Average concentration during gestation.
    out = (AUC[birth_idx] - AUC[conception_idx]) / (times[birth_idx]
      - times[conception_idx])
  } else if (DM_code == 4) {  # Average concentration during nursing.
    out = (AUC[wean_idx] - AUC[birth_idx]) / (times[wean_idx]
      - times[birth_idx])
  } else if (DM_code == 5) {  # Average concentration from conception to
                              # end of simulation.
    out = (AUC[length(AUC)] - AUC[conception_idx]) / (times[length(times)]
      - times[conception_idx])
  } else if (DM_code == 6) {  # Average concentration during entire simulation.
    out = (AUC[length(AUC)] - AUC[1]) / (times[length(times)] - times[1])
  }
  else {
    stop("Dose metric code is not recognized.")
  }
  return(out)
}


cost_fun <- function(d_m, DM_code, DM_val, M_m_df1=NULL, M_m_df2=NULL,
                     M_m_df3=NULL, M_i_df1=NULL, M_i_df2=NULL,
                     preg=TRUE, human_age=NULL, human_HL=NULL) {
    # Define simulation parameters.
    p = c(d_m=d_m)              # Dose rate (mg/kg/d) to human mother.
    p = init_human_p(p)
    if (!is.null(human_HL)) {
        p["half_life"] = human_HL
    }
    
    # Define final age if preg is FALSE and human_age is non-Null.
    if (preg) {
        if (DM_code < 5) {
            times=NULL
        } else {
            if (is.null(human_age)) {
                t_end = 78.75 * 365             # Lifetime of filial human (d),
            }                                   #  including time in-utero.
            else {
                t_end = human_age + 0.75 * 365  # Lifetime of filial human (d),
            }                                   #  including time in-utero.
            t_start = -24.25 * 365              # Birth of mother (d).
            times = seq(from=t_start, to=t_end, by=0.25)
        }
    } else {
        if (is.null(human_age)) {
            t_end = 78 * 365
        } else {
            t_end = human_age
        }
        times = seq(from=0, to=t_end, by=1)
    }
    # Run simulation.
    out <- human_sim(times=times, p=p, M_m_df1=M_m_df1, M_m_df2=M_m_df2,
                     M_m_df3=M_m_df3, M_i_df1=M_i_df1, M_i_df2=M_i_df2,
                     preg=preg)
    
    # Compute human dose metric.
    if (preg && (DM_code <= 5)) {
        DM_human = comp_dose_metric(out[ , "time"], out[ , "C_i"],
                                    out[ , "AUC_i"], p[["t_gest"]],
                                    p[["t_lact"]], DM_code)
    } else {
        DM_human = comp_dose_metric(out[ , "time"], out[ , "C_m"],
                                    out[ , "AUC_m"], p[["t_gest"]],
                                    p[["t_lact"]], DM_code)
    }
    # Cost is square of the difference between the human dose metric and the
    # nominal dose metric value.
    cost = (DM_human - DM_val) ** 2
    return(cost)
}


comp_hed <- function(DM_code, DM_val, M_m_df1=NULL, M_m_df2=NULL,
                     M_m_df3=NULL, M_i_df1=NULL, M_i_df2=NULL,
                     preg=TRUE, human_age=NULL, human_HL=NULL) {
  opt_result = optimize(cost_fun, c(0, 1e6), DM_code, DM_val,
                        M_m_df1=M_m_df1, M_m_df2=M_m_df2, M_m_df3=M_m_df3,
                        M_i_df1=M_i_df1, M_i_df2=M_i_df2, preg=preg,
                        human_age=human_age, human_HL=human_HL,
                        tol=1e-8)
  return(opt_result$minimum)
}



hed_demo1 <- function() {
  # Compute human equivalent doses for various dose metrics for one particular
  # developmental study in rats.
  
  # Get human maternal mass dataframes.
  M_m_df1 = read.csv("human_female_mass_0_to_20.csv", header=FALSE,
                     col.names=c("Age (y)", "Mass (kg)"), check.names=FALSE)
  M_m_df2 = read.csv("human_female_mass_20_to_25_pregnancy.csv",
                     header=FALSE, col.names=c("Age (y)", "Mass (kg)"),
                     check.names=FALSE)
  M_m_df3 = read.csv("human_female_mass_25_to_26_postnatal.csv",
                     header=FALSE, col.names=c("Age (y)", "Mass (kg)"),
                     check.names=FALSE)

  # Get human infant mass dataframes.
  M_i_df1 = read.csv("human_female_mass_0_to_20.csv", header=FALSE,
                     col.names=c("Age (y)", "Mass (kg)"), check.names=FALSE)
  M_i_df2 = read.csv("human_female_mass_20_to_75.csv", header=FALSE,
                     col.names=c("Age (y)", "Mass (kg)"), check.names=FALSE)

  # Define parameters for rat experiment.
  p_rat = c(d_m = 6,          # Dose rate (mg/kg/d) to mother.
            t_m_start = 6,    # Time (d) since conception maternal dose starts.
            t_m_end = 28,     # Time (d) since conception maternal dose ends.
            t_i_end = 50)     # Time (d) since conception infant dose ends.
  
  p_rat = init_rat_p(p_rat)
  
  # Run simulation of rat experiment.
  out_rat <- rat_sim(p=p_rat)
  
  # # Plot all output variables vs. time.
  # out = out_rat
  # for (idx in 2:ncol(out)) {
  #     plot(out[ , 1], out[ , idx], type='l', xlab="Time (d)",
  #          ylab=colnames(out)[idx])
  # }
  
  # Dose metric codes and corresponding descriptions
  DM_code_vec = c(1, 2, 3, 4, 5)
  desc_vec1 = c("peak concentration",
                "average concentration",
                "average concentration",
                "average concentration",
                "average concentration")
  desc_vec2 = c("fetus/infant",
                "fetus/infant",
                "fetus",
                "infant",
                "fetus/infant")
  desc_vec3 = c("gestation and nursing",
                "gestation and nursing",
                "gestation",
                "nursing",
                "the entire simulation")
  for (idx in seq(length(DM_code_vec))) {
    DM_code = DM_code_vec[idx]
    DM_rat = comp_dose_metric(out_rat[ , "time"], out_rat[ , "C_i"],
                              out_rat[ , "AUC_i"], p_rat["t_gest"],
                              p_rat["t_lact"], DM_code)
    
    # Compute human equivalent dose.
    HED = comp_hed(DM_code, DM_rat, M_m_df1=M_m_df1, M_m_df2=M_m_df2,
                   M_m_df3=M_m_df3, M_i_df1=M_i_df1, M_i_df2=M_i_df2,
                   preg=TRUE)
    
    # Run simulation of human exposure at HED.
    p_human = c(d_m=HED)
    p_human = init_human_p(p_human)
    if (DM_code < 5) {
      times=NULL
    } else {
      t_end = 78.75 * 365     # Lifetime of filial human (d), including
                              #  time in-utero.
      t_start = -24.25 * 365  # Birth of mother (d).
      times = seq(from=t_start, to=t_end, by=0.25)
    }
    out_human <- human_sim(times=times, p=p_human, M_m_df1=M_m_df1,
                           M_m_df2=M_m_df2, M_m_df3=M_m_df3, M_i_df1=M_i_df1,
                           M_i_df2=M_i_df2, preg=TRUE)
    
    # Compute dose metric for human.
    DM_human = comp_dose_metric(out_human[ , "time"], out_human[ , "C_i"],
                                out_human[ , "AUC_i"], p_human["t_gest"],
                                p_human["t_lact"], DM_code)
    
    cat("Dose Metric #", DM_code, ":\n", sep="")
    cat("   -Rat dose", p_rat[["d_m"]], "mg/kg/d produces", desc_vec1[idx],
        DM_rat, "mg/kg in", desc_vec2[idx], "\n    during", desc_vec3[idx],
        "\n")
    cat("   -Human dose", p_human[["d_m"]], "mg/kg/d produces", desc_vec1[idx],
        DM_human, "mg/kg in", desc_vec2[idx], "\n    during", desc_vec3[idx],
        "\n")
  }
}